// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: hub.proto

package orchestrationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agent struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name           *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Role           *string                `protobuf:"bytes,3,opt,name=role"`
	xxx_hidden_OrganizationId *string                `protobuf:"bytes,4,opt,name=organization_id,json=organizationId"`
	xxx_hidden_Status         *string                `protobuf:"bytes,5,opt,name=status"`
	xxx_hidden_ProviderType   *string                `protobuf:"bytes,6,opt,name=provider_type,json=providerType"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Agent) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Agent) GetRole() string {
	if x != nil {
		if x.xxx_hidden_Role != nil {
			return *x.xxx_hidden_Role
		}
		return ""
	}
	return ""
}

func (x *Agent) GetOrganizationId() string {
	if x != nil {
		if x.xxx_hidden_OrganizationId != nil {
			return *x.xxx_hidden_OrganizationId
		}
		return ""
	}
	return ""
}

func (x *Agent) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *Agent) GetProviderType() string {
	if x != nil {
		if x.xxx_hidden_ProviderType != nil {
			return *x.xxx_hidden_ProviderType
		}
		return ""
	}
	return ""
}

func (x *Agent) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Agent) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *Agent) SetRole(v string) {
	x.xxx_hidden_Role = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *Agent) SetOrganizationId(v string) {
	x.xxx_hidden_OrganizationId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Agent) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Agent) SetProviderType(v string) {
	x.xxx_hidden_ProviderType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *Agent) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Agent) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Agent) HasRole() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Agent) HasOrganizationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Agent) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Agent) HasProviderType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Agent) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Agent) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Agent) ClearRole() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Role = nil
}

func (x *Agent) ClearOrganizationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_OrganizationId = nil
}

func (x *Agent) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Status = nil
}

func (x *Agent) ClearProviderType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_ProviderType = nil
}

type Agent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             *string
	Name           *string
	Role           *string
	OrganizationId *string
	Status         *string
	ProviderType   *string
}

func (b0 Agent_builder) Build() *Agent {
	m0 := &Agent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Role != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Role = b.Role
	}
	if b.OrganizationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_OrganizationId = b.OrganizationId
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Status = b.Status
	}
	if b.ProviderType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_ProviderType = b.ProviderType
	}
	return m0
}

type Message struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_FromAgent      *string                `protobuf:"bytes,2,opt,name=from_agent,json=fromAgent"`
	xxx_hidden_ToAgent        *string                `protobuf:"bytes,3,opt,name=to_agent,json=toAgent"`
	xxx_hidden_Type           *string                `protobuf:"bytes,4,opt,name=type"`
	xxx_hidden_Content        *string                `protobuf:"bytes,5,opt,name=content"`
	xxx_hidden_MeetingId      *string                `protobuf:"bytes,6,opt,name=meeting_id,json=meetingId"`
	xxx_hidden_OccurredAtUnix int64                  `protobuf:"varint,7,opt,name=occurred_at_unix,json=occurredAtUnix"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Message) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Message) GetFromAgent() string {
	if x != nil {
		if x.xxx_hidden_FromAgent != nil {
			return *x.xxx_hidden_FromAgent
		}
		return ""
	}
	return ""
}

func (x *Message) GetToAgent() string {
	if x != nil {
		if x.xxx_hidden_ToAgent != nil {
			return *x.xxx_hidden_ToAgent
		}
		return ""
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		if x.xxx_hidden_Content != nil {
			return *x.xxx_hidden_Content
		}
		return ""
	}
	return ""
}

func (x *Message) GetMeetingId() string {
	if x != nil {
		if x.xxx_hidden_MeetingId != nil {
			return *x.xxx_hidden_MeetingId
		}
		return ""
	}
	return ""
}

func (x *Message) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.xxx_hidden_OccurredAtUnix
	}
	return 0
}

func (x *Message) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Message) SetFromAgent(v string) {
	x.xxx_hidden_FromAgent = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *Message) SetToAgent(v string) {
	x.xxx_hidden_ToAgent = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *Message) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *Message) SetContent(v string) {
	x.xxx_hidden_Content = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *Message) SetMeetingId(v string) {
	x.xxx_hidden_MeetingId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *Message) SetOccurredAtUnix(v int64) {
	x.xxx_hidden_OccurredAtUnix = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *Message) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Message) HasFromAgent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Message) HasToAgent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Message) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Message) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Message) HasMeetingId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Message) HasOccurredAtUnix() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Message) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Message) ClearFromAgent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_FromAgent = nil
}

func (x *Message) ClearToAgent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ToAgent = nil
}

func (x *Message) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Type = nil
}

func (x *Message) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Content = nil
}

func (x *Message) ClearMeetingId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_MeetingId = nil
}

func (x *Message) ClearOccurredAtUnix() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_OccurredAtUnix = 0
}

type Message_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             *string
	FromAgent      *string
	ToAgent        *string
	Type           *string
	Content        *string
	MeetingId      *string
	OccurredAtUnix *int64
}

func (b0 Message_builder) Build() *Message {
	m0 := &Message{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	if b.FromAgent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_FromAgent = b.FromAgent
	}
	if b.ToAgent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_ToAgent = b.ToAgent
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Type = b.Type
	}
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Content = b.Content
	}
	if b.MeetingId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_MeetingId = b.MeetingId
	}
	if b.OccurredAtUnix != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_OccurredAtUnix = *b.OccurredAtUnix
	}
	return m0
}

type MeetingRoom struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Agenda       *string                `protobuf:"bytes,2,opt,name=agenda"`
	xxx_hidden_Participants []string               `protobuf:"bytes,3,rep,name=participants"`
	xxx_hidden_Transcript   *[]*Message            `protobuf:"bytes,4,rep,name=transcript"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MeetingRoom) Reset() {
	*x = MeetingRoom{}
	mi := &file_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoom) ProtoMessage() {}

func (x *MeetingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MeetingRoom) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *MeetingRoom) GetAgenda() string {
	if x != nil {
		if x.xxx_hidden_Agenda != nil {
			return *x.xxx_hidden_Agenda
		}
		return ""
	}
	return ""
}

func (x *MeetingRoom) GetParticipants() []string {
	if x != nil {
		return x.xxx_hidden_Participants
	}
	return nil
}

func (x *MeetingRoom) GetTranscript() []*Message {
	if x != nil {
		if x.xxx_hidden_Transcript != nil {
			return *x.xxx_hidden_Transcript
		}
	}
	return nil
}

func (x *MeetingRoom) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *MeetingRoom) SetAgenda(v string) {
	x.xxx_hidden_Agenda = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *MeetingRoom) SetParticipants(v []string) {
	x.xxx_hidden_Participants = v
}

func (x *MeetingRoom) SetTranscript(v []*Message) {
	x.xxx_hidden_Transcript = &v
}

func (x *MeetingRoom) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MeetingRoom) HasAgenda() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MeetingRoom) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *MeetingRoom) ClearAgenda() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Agenda = nil
}

type MeetingRoom_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           *string
	Agenda       *string
	Participants []string
	Transcript   []*Message
}

func (b0 MeetingRoom_builder) Build() *MeetingRoom {
	m0 := &MeetingRoom{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	if b.Agenda != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Agenda = b.Agenda
	}
	x.xxx_hidden_Participants = b.Participants
	x.xxx_hidden_Transcript = &b.Transcript
	return m0
}

type RegisterAgentRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Agent *Agent                 `protobuf:"bytes,1,opt,name=agent"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterAgentRequest) GetAgent() *Agent {
	if x != nil {
		return x.xxx_hidden_Agent
	}
	return nil
}

func (x *RegisterAgentRequest) SetAgent(v *Agent) {
	x.xxx_hidden_Agent = v
}

func (x *RegisterAgentRequest) HasAgent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Agent != nil
}

func (x *RegisterAgentRequest) ClearAgent() {
	x.xxx_hidden_Agent = nil
}

type RegisterAgentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Agent *Agent
}

func (b0 RegisterAgentRequest_builder) Build() *RegisterAgentRequest {
	m0 := &RegisterAgentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Agent = b.Agent
	return m0
}

type RegisterAgentResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *RegisterAgentResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RegisterAgentResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterAgentResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type RegisterAgentResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 RegisterAgentResponse_builder) Build() *RegisterAgentResponse {
	m0 := &RegisterAgentResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

type OpenMeetingRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MeetingId    *string                `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId"`
	xxx_hidden_Agenda       *string                `protobuf:"bytes,2,opt,name=agenda"`
	xxx_hidden_Participants []string               `protobuf:"bytes,3,rep,name=participants"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OpenMeetingRequest) Reset() {
	*x = OpenMeetingRequest{}
	mi := &file_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenMeetingRequest) ProtoMessage() {}

func (x *OpenMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OpenMeetingRequest) GetMeetingId() string {
	if x != nil {
		if x.xxx_hidden_MeetingId != nil {
			return *x.xxx_hidden_MeetingId
		}
		return ""
	}
	return ""
}

func (x *OpenMeetingRequest) GetAgenda() string {
	if x != nil {
		if x.xxx_hidden_Agenda != nil {
			return *x.xxx_hidden_Agenda
		}
		return ""
	}
	return ""
}

func (x *OpenMeetingRequest) GetParticipants() []string {
	if x != nil {
		return x.xxx_hidden_Participants
	}
	return nil
}

func (x *OpenMeetingRequest) SetMeetingId(v string) {
	x.xxx_hidden_MeetingId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *OpenMeetingRequest) SetAgenda(v string) {
	x.xxx_hidden_Agenda = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *OpenMeetingRequest) SetParticipants(v []string) {
	x.xxx_hidden_Participants = v
}

func (x *OpenMeetingRequest) HasMeetingId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OpenMeetingRequest) HasAgenda() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OpenMeetingRequest) ClearMeetingId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MeetingId = nil
}

func (x *OpenMeetingRequest) ClearAgenda() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Agenda = nil
}

type OpenMeetingRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MeetingId    *string
	Agenda       *string
	Participants []string
}

func (b0 OpenMeetingRequest_builder) Build() *OpenMeetingRequest {
	m0 := &OpenMeetingRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MeetingId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_MeetingId = b.MeetingId
	}
	if b.Agenda != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Agenda = b.Agenda
	}
	x.xxx_hidden_Participants = b.Participants
	return m0
}

type PublishMessageRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message *Message               `protobuf:"bytes,1,opt,name=message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PublishMessageRequest) Reset() {
	*x = PublishMessageRequest{}
	mi := &file_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessageRequest) ProtoMessage() {}

func (x *PublishMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublishMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return nil
}

func (x *PublishMessageRequest) SetMessage(v *Message) {
	x.xxx_hidden_Message = v
}

func (x *PublishMessageRequest) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *PublishMessageRequest) ClearMessage() {
	x.xxx_hidden_Message = nil
}

type PublishMessageRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Message *Message
}

func (b0 PublishMessageRequest_builder) Build() *PublishMessageRequest {
	m0 := &PublishMessageRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Message = b.Message
	return m0
}

type PublishMessageResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PublishMessageResponse) Reset() {
	*x = PublishMessageResponse{}
	mi := &file_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessageResponse) ProtoMessage() {}

func (x *PublishMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublishMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *PublishMessageResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PublishMessageResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PublishMessageResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type PublishMessageResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 PublishMessageResponse_builder) Build() *PublishMessageResponse {
	m0 := &PublishMessageResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

type DelegateTaskRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FromAgentId *string                `protobuf:"bytes,1,opt,name=from_agent_id,json=fromAgentId"`
	xxx_hidden_ToAgentId   *string                `protobuf:"bytes,2,opt,name=to_agent_id,json=toAgentId"`
	xxx_hidden_Task        *Message               `protobuf:"bytes,3,opt,name=task"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DelegateTaskRequest) Reset() {
	*x = DelegateTaskRequest{}
	mi := &file_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateTaskRequest) ProtoMessage() {}

func (x *DelegateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DelegateTaskRequest) GetFromAgentId() string {
	if x != nil {
		if x.xxx_hidden_FromAgentId != nil {
			return *x.xxx_hidden_FromAgentId
		}
		return ""
	}
	return ""
}

func (x *DelegateTaskRequest) GetToAgentId() string {
	if x != nil {
		if x.xxx_hidden_ToAgentId != nil {
			return *x.xxx_hidden_ToAgentId
		}
		return ""
	}
	return ""
}

func (x *DelegateTaskRequest) GetTask() *Message {
	if x != nil {
		return x.xxx_hidden_Task
	}
	return nil
}

func (x *DelegateTaskRequest) SetFromAgentId(v string) {
	x.xxx_hidden_FromAgentId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *DelegateTaskRequest) SetToAgentId(v string) {
	x.xxx_hidden_ToAgentId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *DelegateTaskRequest) SetTask(v *Message) {
	x.xxx_hidden_Task = v
}

func (x *DelegateTaskRequest) HasFromAgentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DelegateTaskRequest) HasToAgentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DelegateTaskRequest) HasTask() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Task != nil
}

func (x *DelegateTaskRequest) ClearFromAgentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FromAgentId = nil
}

func (x *DelegateTaskRequest) ClearToAgentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ToAgentId = nil
}

func (x *DelegateTaskRequest) ClearTask() {
	x.xxx_hidden_Task = nil
}

type DelegateTaskRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FromAgentId *string
	ToAgentId   *string
	Task        *Message
}

func (b0 DelegateTaskRequest_builder) Build() *DelegateTaskRequest {
	m0 := &DelegateTaskRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FromAgentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_FromAgentId = b.FromAgentId
	}
	if b.ToAgentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ToAgentId = b.ToAgentId
	}
	x.xxx_hidden_Task = b.Task
	return m0
}

type DelegateTaskResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DelegateTaskResponse) Reset() {
	*x = DelegateTaskResponse{}
	mi := &file_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateTaskResponse) ProtoMessage() {}

func (x *DelegateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DelegateTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *DelegateTaskResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DelegateTaskResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DelegateTaskResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type DelegateTaskResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 DelegateTaskResponse_builder) Build() *DelegateTaskResponse {
	m0 := &DelegateTaskResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

type SubTask struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TaskId         *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId"`
	xxx_hidden_TargetRole     *string                `protobuf:"bytes,2,opt,name=target_role,json=targetRole"`
	xxx_hidden_Instruction    *string                `protobuf:"bytes,3,opt,name=instruction"`
	xxx_hidden_ParentThreadId *string                `protobuf:"bytes,4,opt,name=parent_thread_id,json=parentThreadId"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SubTask) Reset() {
	*x = SubTask{}
	mi := &file_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubTask) ProtoMessage() {}

func (x *SubTask) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SubTask) GetTaskId() string {
	if x != nil {
		if x.xxx_hidden_TaskId != nil {
			return *x.xxx_hidden_TaskId
		}
		return ""
	}
	return ""
}

func (x *SubTask) GetTargetRole() string {
	if x != nil {
		if x.xxx_hidden_TargetRole != nil {
			return *x.xxx_hidden_TargetRole
		}
		return ""
	}
	return ""
}

func (x *SubTask) GetInstruction() string {
	if x != nil {
		if x.xxx_hidden_Instruction != nil {
			return *x.xxx_hidden_Instruction
		}
		return ""
	}
	return ""
}

func (x *SubTask) GetParentThreadId() string {
	if x != nil {
		if x.xxx_hidden_ParentThreadId != nil {
			return *x.xxx_hidden_ParentThreadId
		}
		return ""
	}
	return ""
}

func (x *SubTask) SetTaskId(v string) {
	x.xxx_hidden_TaskId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *SubTask) SetTargetRole(v string) {
	x.xxx_hidden_TargetRole = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *SubTask) SetInstruction(v string) {
	x.xxx_hidden_Instruction = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *SubTask) SetParentThreadId(v string) {
	x.xxx_hidden_ParentThreadId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *SubTask) HasTaskId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SubTask) HasTargetRole() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SubTask) HasInstruction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SubTask) HasParentThreadId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SubTask) ClearTaskId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TaskId = nil
}

func (x *SubTask) ClearTargetRole() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TargetRole = nil
}

func (x *SubTask) ClearInstruction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Instruction = nil
}

func (x *SubTask) ClearParentThreadId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ParentThreadId = nil
}

type SubTask_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TaskId         *string
	TargetRole     *string
	Instruction    *string
	ParentThreadId *string
}

func (b0 SubTask_builder) Build() *SubTask {
	m0 := &SubTask{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TaskId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_TaskId = b.TaskId
	}
	if b.TargetRole != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_TargetRole = b.TargetRole
	}
	if b.Instruction != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Instruction = b.Instruction
	}
	if b.ParentThreadId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ParentThreadId = b.ParentThreadId
	}
	return m0
}

type TokenEfficientContextSummarizationEvent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventId     *string                `protobuf:"bytes,1,opt,name=event_id,json=eventId"`
	xxx_hidden_AgentId     *string                `protobuf:"bytes,2,opt,name=agent_id,json=agentId"`
	xxx_hidden_Payload     []byte                 `protobuf:"bytes,3,opt,name=payload"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TokenEfficientContextSummarizationEvent) Reset() {
	*x = TokenEfficientContextSummarizationEvent{}
	mi := &file_hub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenEfficientContextSummarizationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEfficientContextSummarizationEvent) ProtoMessage() {}

func (x *TokenEfficientContextSummarizationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TokenEfficientContextSummarizationEvent) GetEventId() string {
	if x != nil {
		if x.xxx_hidden_EventId != nil {
			return *x.xxx_hidden_EventId
		}
		return ""
	}
	return ""
}

func (x *TokenEfficientContextSummarizationEvent) GetAgentId() string {
	if x != nil {
		if x.xxx_hidden_AgentId != nil {
			return *x.xxx_hidden_AgentId
		}
		return ""
	}
	return ""
}

func (x *TokenEfficientContextSummarizationEvent) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *TokenEfficientContextSummarizationEvent) SetEventId(v string) {
	x.xxx_hidden_EventId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *TokenEfficientContextSummarizationEvent) SetAgentId(v string) {
	x.xxx_hidden_AgentId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *TokenEfficientContextSummarizationEvent) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *TokenEfficientContextSummarizationEvent) HasEventId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TokenEfficientContextSummarizationEvent) HasAgentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TokenEfficientContextSummarizationEvent) HasPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TokenEfficientContextSummarizationEvent) ClearEventId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EventId = nil
}

func (x *TokenEfficientContextSummarizationEvent) ClearAgentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AgentId = nil
}

func (x *TokenEfficientContextSummarizationEvent) ClearPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Payload = nil
}

type TokenEfficientContextSummarizationEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventId *string
	AgentId *string
	Payload []byte
}

func (b0 TokenEfficientContextSummarizationEvent_builder) Build() *TokenEfficientContextSummarizationEvent {
	m0 := &TokenEfficientContextSummarizationEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EventId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_EventId = b.EventId
	}
	if b.AgentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_AgentId = b.AgentId
	}
	if b.Payload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Payload = b.Payload
	}
	return m0
}

type ToolParameterAutoCorrectionEvent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventId     *string                `protobuf:"bytes,1,opt,name=event_id,json=eventId"`
	xxx_hidden_AgentId     *string                `protobuf:"bytes,2,opt,name=agent_id,json=agentId"`
	xxx_hidden_Payload     []byte                 `protobuf:"bytes,3,opt,name=payload"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolParameterAutoCorrectionEvent) Reset() {
	*x = ToolParameterAutoCorrectionEvent{}
	mi := &file_hub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolParameterAutoCorrectionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolParameterAutoCorrectionEvent) ProtoMessage() {}

func (x *ToolParameterAutoCorrectionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolParameterAutoCorrectionEvent) GetEventId() string {
	if x != nil {
		if x.xxx_hidden_EventId != nil {
			return *x.xxx_hidden_EventId
		}
		return ""
	}
	return ""
}

func (x *ToolParameterAutoCorrectionEvent) GetAgentId() string {
	if x != nil {
		if x.xxx_hidden_AgentId != nil {
			return *x.xxx_hidden_AgentId
		}
		return ""
	}
	return ""
}

func (x *ToolParameterAutoCorrectionEvent) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *ToolParameterAutoCorrectionEvent) SetEventId(v string) {
	x.xxx_hidden_EventId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ToolParameterAutoCorrectionEvent) SetAgentId(v string) {
	x.xxx_hidden_AgentId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ToolParameterAutoCorrectionEvent) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ToolParameterAutoCorrectionEvent) HasEventId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ToolParameterAutoCorrectionEvent) HasAgentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ToolParameterAutoCorrectionEvent) HasPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ToolParameterAutoCorrectionEvent) ClearEventId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EventId = nil
}

func (x *ToolParameterAutoCorrectionEvent) ClearAgentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AgentId = nil
}

func (x *ToolParameterAutoCorrectionEvent) ClearPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Payload = nil
}

type ToolParameterAutoCorrectionEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventId *string
	AgentId *string
	Payload []byte
}

func (b0 ToolParameterAutoCorrectionEvent_builder) Build() *ToolParameterAutoCorrectionEvent {
	m0 := &ToolParameterAutoCorrectionEvent{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EventId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_EventId = b.EventId
	}
	if b.AgentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_AgentId = b.AgentId
	}
	if b.Payload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Payload = b.Payload
	}
	return m0
}

type StreamMessagesRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AgentId     *string                `protobuf:"bytes,1,opt,name=agent_id,json=agentId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_hub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamMessagesRequest) GetAgentId() string {
	if x != nil {
		if x.xxx_hidden_AgentId != nil {
			return *x.xxx_hidden_AgentId
		}
		return ""
	}
	return ""
}

func (x *StreamMessagesRequest) SetAgentId(v string) {
	x.xxx_hidden_AgentId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StreamMessagesRequest) HasAgentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamMessagesRequest) ClearAgentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AgentId = nil
}

type StreamMessagesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AgentId *string
}

func (b0 StreamMessagesRequest_builder) Build() *StreamMessagesRequest {
	m0 := &StreamMessagesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AgentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_AgentId = b.AgentId
	}
	return m0
}

type ReasonRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Prompt      *string                `protobuf:"bytes,1,opt,name=prompt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReasonRequest) Reset() {
	*x = ReasonRequest{}
	mi := &file_hub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasonRequest) ProtoMessage() {}

func (x *ReasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReasonRequest) GetPrompt() string {
	if x != nil {
		if x.xxx_hidden_Prompt != nil {
			return *x.xxx_hidden_Prompt
		}
		return ""
	}
	return ""
}

func (x *ReasonRequest) SetPrompt(v string) {
	x.xxx_hidden_Prompt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ReasonRequest) HasPrompt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReasonRequest) ClearPrompt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Prompt = nil
}

type ReasonRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Prompt *string
}

func (b0 ReasonRequest_builder) Build() *ReasonRequest {
	m0 := &ReasonRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Prompt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Prompt = b.Prompt
	}
	return m0
}

type ReasonResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Content     *string                `protobuf:"bytes,1,opt,name=content"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReasonResponse) Reset() {
	*x = ReasonResponse{}
	mi := &file_hub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasonResponse) ProtoMessage() {}

func (x *ReasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReasonResponse) GetContent() string {
	if x != nil {
		if x.xxx_hidden_Content != nil {
			return *x.xxx_hidden_Content
		}
		return ""
	}
	return ""
}

func (x *ReasonResponse) SetContent(v string) {
	x.xxx_hidden_Content = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ReasonResponse) HasContent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReasonResponse) ClearContent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Content = nil
}

type ReasonResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Content *string
}

func (b0 ReasonResponse_builder) Build() *ReasonResponse {
	m0 := &ReasonResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Content != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Content = b.Content
	}
	return m0
}

var File_hub_proto protoreflect.FileDescriptor

const file_hub_proto_rawDesc = "" +
	"\n" +
	"\thub.proto\x12\x11ohc.orchestration\"\xa5\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rprovider_type\x18\x06 \x01(\tR\fproviderType\"\xca\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x02 \x01(\tR\tfromAgent\x12\x19\n" +
	"\bto_agent\x18\x03 \x01(\tR\atoAgent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x06 \x01(\tR\tmeetingId\x12(\n" +
	"\x10occurred_at_unix\x18\a \x01(\x03R\x0eoccurredAtUnix\"\x95\x01\n" +
	"\vMeetingRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06agenda\x18\x02 \x01(\tR\x06agenda\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\tR\fparticipants\x12:\n" +
	"\n" +
	"transcript\x18\x04 \x03(\v2\x1a.ohc.orchestration.MessageR\n" +
	"transcript\"F\n" +
	"\x14RegisterAgentRequest\x12.\n" +
	"\x05agent\x18\x01 \x01(\v2\x18.ohc.orchestration.AgentR\x05agent\"1\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"o\n" +
	"\x12OpenMeetingRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x16\n" +
	"\x06agenda\x18\x02 \x01(\tR\x06agenda\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\tR\fparticipants\"M\n" +
	"\x15PublishMessageRequest\x124\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.ohc.orchestration.MessageR\amessage\"2\n" +
	"\x16PublishMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x89\x01\n" +
	"\x13DelegateTaskRequest\x12\"\n" +
	"\rfrom_agent_id\x18\x01 \x01(\tR\vfromAgentId\x12\x1e\n" +
	"\vto_agent_id\x18\x02 \x01(\tR\ttoAgentId\x12.\n" +
	"\x04task\x18\x03 \x01(\v2\x1a.ohc.orchestration.MessageR\x04task\"0\n" +
	"\x14DelegateTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8f\x01\n" +
	"\aSubTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vtarget_role\x18\x02 \x01(\tR\n" +
	"targetRole\x12 \n" +
	"\vinstruction\x18\x03 \x01(\tR\vinstruction\x12(\n" +
	"\x10parent_thread_id\x18\x04 \x01(\tR\x0eparentThreadId\"y\n" +
	"'TokenEfficientContextSummarizationEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"r\n" +
	" ToolParameterAutoCorrectionEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"2\n" +
	"\x15StreamMessagesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"'\n" +
	"\rReasonRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"*\n" +
	"\x0eReasonResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2\x88\x05\n" +
	"\n" +
	"HubService\x12b\n" +
	"\rRegisterAgent\x12'.ohc.orchestration.RegisterAgentRequest\x1a(.ohc.orchestration.RegisterAgentResponse\x12T\n" +
	"\vOpenMeeting\x12%.ohc.orchestration.OpenMeetingRequest\x1a\x1e.ohc.orchestration.MeetingRoom\x12^\n" +
	"\aPublish\x12(.ohc.orchestration.PublishMessageRequest\x1a).ohc.orchestration.PublishMessageResponse\x12_\n" +
	"\fDelegateTask\x12&.ohc.orchestration.DelegateTaskRequest\x1a'.ohc.orchestration.DelegateTaskResponse\x12X\n" +
	"\x0eStreamMessages\x12(.ohc.orchestration.StreamMessagesRequest\x1a\x1a.ohc.orchestration.Message0\x01\x12M\n" +
	"\x06Reason\x12 .ohc.orchestration.ReasonRequest\x1a!.ohc.orchestration.ReasonResponse\x12V\n" +
	"\x0fDelegateSubTask\x12\x1a.ohc.orchestration.SubTask\x1a'.ohc.orchestration.DelegateTaskResponseB9Z7github.com/onehumancorp/mono/srcs/proto;orchestrationpbb\beditionsp\xe9\a"

var file_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_hub_proto_goTypes = []any{
	(*Agent)(nil),                                   // 0: ohc.orchestration.Agent
	(*Message)(nil),                                 // 1: ohc.orchestration.Message
	(*MeetingRoom)(nil),                             // 2: ohc.orchestration.MeetingRoom
	(*RegisterAgentRequest)(nil),                    // 3: ohc.orchestration.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),                   // 4: ohc.orchestration.RegisterAgentResponse
	(*OpenMeetingRequest)(nil),                      // 5: ohc.orchestration.OpenMeetingRequest
	(*PublishMessageRequest)(nil),                   // 6: ohc.orchestration.PublishMessageRequest
	(*PublishMessageResponse)(nil),                  // 7: ohc.orchestration.PublishMessageResponse
	(*DelegateTaskRequest)(nil),                     // 8: ohc.orchestration.DelegateTaskRequest
	(*DelegateTaskResponse)(nil),                    // 9: ohc.orchestration.DelegateTaskResponse
	(*SubTask)(nil),                                 // 10: ohc.orchestration.SubTask
	(*TokenEfficientContextSummarizationEvent)(nil), // 11: ohc.orchestration.TokenEfficientContextSummarizationEvent
	(*ToolParameterAutoCorrectionEvent)(nil),        // 12: ohc.orchestration.ToolParameterAutoCorrectionEvent
	(*StreamMessagesRequest)(nil),                   // 13: ohc.orchestration.StreamMessagesRequest
	(*ReasonRequest)(nil),                           // 14: ohc.orchestration.ReasonRequest
	(*ReasonResponse)(nil),                          // 15: ohc.orchestration.ReasonResponse
}
var file_hub_proto_depIdxs = []int32{
	1,  // 0: ohc.orchestration.MeetingRoom.transcript:type_name -> ohc.orchestration.Message
	0,  // 1: ohc.orchestration.RegisterAgentRequest.agent:type_name -> ohc.orchestration.Agent
	1,  // 2: ohc.orchestration.PublishMessageRequest.message:type_name -> ohc.orchestration.Message
	1,  // 3: ohc.orchestration.DelegateTaskRequest.task:type_name -> ohc.orchestration.Message
	3,  // 4: ohc.orchestration.HubService.RegisterAgent:input_type -> ohc.orchestration.RegisterAgentRequest
	5,  // 5: ohc.orchestration.HubService.OpenMeeting:input_type -> ohc.orchestration.OpenMeetingRequest
	6,  // 6: ohc.orchestration.HubService.Publish:input_type -> ohc.orchestration.PublishMessageRequest
	8,  // 7: ohc.orchestration.HubService.DelegateTask:input_type -> ohc.orchestration.DelegateTaskRequest
	13, // 8: ohc.orchestration.HubService.StreamMessages:input_type -> ohc.orchestration.StreamMessagesRequest
	14, // 9: ohc.orchestration.HubService.Reason:input_type -> ohc.orchestration.ReasonRequest
	10, // 10: ohc.orchestration.HubService.DelegateSubTask:input_type -> ohc.orchestration.SubTask
	4,  // 11: ohc.orchestration.HubService.RegisterAgent:output_type -> ohc.orchestration.RegisterAgentResponse
	2,  // 12: ohc.orchestration.HubService.OpenMeeting:output_type -> ohc.orchestration.MeetingRoom
	7,  // 13: ohc.orchestration.HubService.Publish:output_type -> ohc.orchestration.PublishMessageResponse
	9,  // 14: ohc.orchestration.HubService.DelegateTask:output_type -> ohc.orchestration.DelegateTaskResponse
	1,  // 15: ohc.orchestration.HubService.StreamMessages:output_type -> ohc.orchestration.Message
	15, // 16: ohc.orchestration.HubService.Reason:output_type -> ohc.orchestration.ReasonResponse
	9,  // 17: ohc.orchestration.HubService.DelegateSubTask:output_type -> ohc.orchestration.DelegateTaskResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hub_proto_init() }
func file_hub_proto_init() {
	if File_hub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_proto_rawDesc), len(file_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_proto_goTypes,
		DependencyIndexes: file_hub_proto_depIdxs,
		MessageInfos:      file_hub_proto_msgTypes,
	}.Build()
	File_hub_proto = out.File
	file_hub_proto_goTypes = nil
	file_hub_proto_depIdxs = nil
}
