// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hub.proto

package orchestrationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	OrganizationId string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ProviderType   string                 `protobuf:"bytes,6,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Agent) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromAgent      string                 `protobuf:"bytes,2,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	ToAgent        string                 `protobuf:"bytes,3,opt,name=to_agent,json=toAgent,proto3" json:"to_agent,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MeetingId      string                 `protobuf:"bytes,6,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,7,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *Message) GetToAgent() string {
	if x != nil {
		return x.ToAgent
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *Message) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

type MeetingRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Agenda        string                 `protobuf:"bytes,2,opt,name=agenda,proto3" json:"agenda,omitempty"`
	Participants  []string               `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	Transcript    []*Message             `protobuf:"bytes,4,rep,name=transcript,proto3" json:"transcript,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingRoom) Reset() {
	*x = MeetingRoom{}
	mi := &file_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingRoom) ProtoMessage() {}

func (x *MeetingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingRoom.ProtoReflect.Descriptor instead.
func (*MeetingRoom) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{2}
}

func (x *MeetingRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeetingRoom) GetAgenda() string {
	if x != nil {
		return x.Agenda
	}
	return ""
}

func (x *MeetingRoom) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *MeetingRoom) GetTranscript() []*Message {
	if x != nil {
		return x.Transcript
	}
	return nil
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAgentRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type OpenMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Agenda        string                 `protobuf:"bytes,2,opt,name=agenda,proto3" json:"agenda,omitempty"`
	Participants  []string               `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenMeetingRequest) Reset() {
	*x = OpenMeetingRequest{}
	mi := &file_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenMeetingRequest) ProtoMessage() {}

func (x *OpenMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenMeetingRequest.ProtoReflect.Descriptor instead.
func (*OpenMeetingRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{5}
}

func (x *OpenMeetingRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *OpenMeetingRequest) GetAgenda() string {
	if x != nil {
		return x.Agenda
	}
	return ""
}

func (x *OpenMeetingRequest) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

type PublishMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessageRequest) Reset() {
	*x = PublishMessageRequest{}
	mi := &file_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessageRequest) ProtoMessage() {}

func (x *PublishMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessageRequest.ProtoReflect.Descriptor instead.
func (*PublishMessageRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{6}
}

func (x *PublishMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type PublishMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessageResponse) Reset() {
	*x = PublishMessageResponse{}
	mi := &file_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessageResponse) ProtoMessage() {}

func (x *PublishMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessageResponse.ProtoReflect.Descriptor instead.
func (*PublishMessageResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{7}
}

func (x *PublishMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DelegateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAgentId   string                 `protobuf:"bytes,1,opt,name=from_agent_id,json=fromAgentId,proto3" json:"from_agent_id,omitempty"`
	ToAgentId     string                 `protobuf:"bytes,2,opt,name=to_agent_id,json=toAgentId,proto3" json:"to_agent_id,omitempty"`
	Task          *Message               `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateTaskRequest) Reset() {
	*x = DelegateTaskRequest{}
	mi := &file_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateTaskRequest) ProtoMessage() {}

func (x *DelegateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateTaskRequest.ProtoReflect.Descriptor instead.
func (*DelegateTaskRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{8}
}

func (x *DelegateTaskRequest) GetFromAgentId() string {
	if x != nil {
		return x.FromAgentId
	}
	return ""
}

func (x *DelegateTaskRequest) GetToAgentId() string {
	if x != nil {
		return x.ToAgentId
	}
	return ""
}

func (x *DelegateTaskRequest) GetTask() *Message {
	if x != nil {
		return x.Task
	}
	return nil
}

type DelegateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateTaskResponse) Reset() {
	*x = DelegateTaskResponse{}
	mi := &file_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateTaskResponse) ProtoMessage() {}

func (x *DelegateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateTaskResponse.ProtoReflect.Descriptor instead.
func (*DelegateTaskResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{9}
}

func (x *DelegateTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TargetRole     string                 `protobuf:"bytes,2,opt,name=target_role,json=targetRole,proto3" json:"target_role,omitempty"`
	Instruction    string                 `protobuf:"bytes,3,opt,name=instruction,proto3" json:"instruction,omitempty"`
	ParentThreadId string                 `protobuf:"bytes,4,opt,name=parent_thread_id,json=parentThreadId,proto3" json:"parent_thread_id,omitempty"`
	FromAgentId    string                 `protobuf:"bytes,5,opt,name=from_agent_id,json=fromAgentId,proto3" json:"from_agent_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubTask) Reset() {
	*x = SubTask{}
	mi := &file_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubTask) ProtoMessage() {}

func (x *SubTask) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubTask.ProtoReflect.Descriptor instead.
func (*SubTask) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{10}
}

func (x *SubTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubTask) GetTargetRole() string {
	if x != nil {
		return x.TargetRole
	}
	return ""
}

func (x *SubTask) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *SubTask) GetParentThreadId() string {
	if x != nil {
		return x.ParentThreadId
	}
	return ""
}

func (x *SubTask) GetFromAgentId() string {
	if x != nil {
		return x.FromAgentId
	}
	return ""
}

type TokenEfficientContextSummarizationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenEfficientContextSummarizationEvent) Reset() {
	*x = TokenEfficientContextSummarizationEvent{}
	mi := &file_hub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenEfficientContextSummarizationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEfficientContextSummarizationEvent) ProtoMessage() {}

func (x *TokenEfficientContextSummarizationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEfficientContextSummarizationEvent.ProtoReflect.Descriptor instead.
func (*TokenEfficientContextSummarizationEvent) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{11}
}

func (x *TokenEfficientContextSummarizationEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TokenEfficientContextSummarizationEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TokenEfficientContextSummarizationEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ToolParameterAutoCorrectionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolParameterAutoCorrectionEvent) Reset() {
	*x = ToolParameterAutoCorrectionEvent{}
	mi := &file_hub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolParameterAutoCorrectionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolParameterAutoCorrectionEvent) ProtoMessage() {}

func (x *ToolParameterAutoCorrectionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolParameterAutoCorrectionEvent.ProtoReflect.Descriptor instead.
func (*ToolParameterAutoCorrectionEvent) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{12}
}

func (x *ToolParameterAutoCorrectionEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ToolParameterAutoCorrectionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ToolParameterAutoCorrectionEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StreamMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_hub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{13}
}

func (x *StreamMessagesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ReasonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	FromAgentId   string                 `protobuf:"bytes,2,opt,name=from_agent_id,json=fromAgentId,proto3" json:"from_agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasonRequest) Reset() {
	*x = ReasonRequest{}
	mi := &file_hub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasonRequest) ProtoMessage() {}

func (x *ReasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasonRequest.ProtoReflect.Descriptor instead.
func (*ReasonRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{14}
}

func (x *ReasonRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ReasonRequest) GetFromAgentId() string {
	if x != nil {
		return x.FromAgentId
	}
	return ""
}

type ReasonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasonResponse) Reset() {
	*x = ReasonResponse{}
	mi := &file_hub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasonResponse) ProtoMessage() {}

func (x *ReasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasonResponse.ProtoReflect.Descriptor instead.
func (*ReasonResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{15}
}

func (x *ReasonResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_hub_proto protoreflect.FileDescriptor

const file_hub_proto_rawDesc = "" +
	"\n" +
	"\thub.proto\x12\x11ohc.orchestration\"\xa5\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rprovider_type\x18\x06 \x01(\tR\fproviderType\"\xca\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x02 \x01(\tR\tfromAgent\x12\x19\n" +
	"\bto_agent\x18\x03 \x01(\tR\atoAgent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x06 \x01(\tR\tmeetingId\x12(\n" +
	"\x10occurred_at_unix\x18\a \x01(\x03R\x0eoccurredAtUnix\"\x95\x01\n" +
	"\vMeetingRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06agenda\x18\x02 \x01(\tR\x06agenda\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\tR\fparticipants\x12:\n" +
	"\n" +
	"transcript\x18\x04 \x03(\v2\x1a.ohc.orchestration.MessageR\n" +
	"transcript\"F\n" +
	"\x14RegisterAgentRequest\x12.\n" +
	"\x05agent\x18\x01 \x01(\v2\x18.ohc.orchestration.AgentR\x05agent\"1\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"o\n" +
	"\x12OpenMeetingRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x16\n" +
	"\x06agenda\x18\x02 \x01(\tR\x06agenda\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\tR\fparticipants\"M\n" +
	"\x15PublishMessageRequest\x124\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.ohc.orchestration.MessageR\amessage\"2\n" +
	"\x16PublishMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x89\x01\n" +
	"\x13DelegateTaskRequest\x12\"\n" +
	"\rfrom_agent_id\x18\x01 \x01(\tR\vfromAgentId\x12\x1e\n" +
	"\vto_agent_id\x18\x02 \x01(\tR\ttoAgentId\x12.\n" +
	"\x04task\x18\x03 \x01(\v2\x1a.ohc.orchestration.MessageR\x04task\"0\n" +
	"\x14DelegateTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb3\x01\n" +
	"\aSubTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vtarget_role\x18\x02 \x01(\tR\n" +
	"targetRole\x12 \n" +
	"\vinstruction\x18\x03 \x01(\tR\vinstruction\x12(\n" +
	"\x10parent_thread_id\x18\x04 \x01(\tR\x0eparentThreadId\x12\"\n" +
	"\rfrom_agent_id\x18\x05 \x01(\tR\vfromAgentId\"y\n" +
	"'TokenEfficientContextSummarizationEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"r\n" +
	" ToolParameterAutoCorrectionEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"2\n" +
	"\x15StreamMessagesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"K\n" +
	"\rReasonRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\"\n" +
	"\rfrom_agent_id\x18\x02 \x01(\tR\vfromAgentId\"*\n" +
	"\x0eReasonResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2\x88\x05\n" +
	"\n" +
	"HubService\x12b\n" +
	"\rRegisterAgent\x12'.ohc.orchestration.RegisterAgentRequest\x1a(.ohc.orchestration.RegisterAgentResponse\x12T\n" +
	"\vOpenMeeting\x12%.ohc.orchestration.OpenMeetingRequest\x1a\x1e.ohc.orchestration.MeetingRoom\x12^\n" +
	"\aPublish\x12(.ohc.orchestration.PublishMessageRequest\x1a).ohc.orchestration.PublishMessageResponse\x12_\n" +
	"\fDelegateTask\x12&.ohc.orchestration.DelegateTaskRequest\x1a'.ohc.orchestration.DelegateTaskResponse\x12X\n" +
	"\x0eStreamMessages\x12(.ohc.orchestration.StreamMessagesRequest\x1a\x1a.ohc.orchestration.Message0\x01\x12M\n" +
	"\x06Reason\x12 .ohc.orchestration.ReasonRequest\x1a!.ohc.orchestration.ReasonResponse\x12V\n" +
	"\x0fDelegateSubTask\x12\x1a.ohc.orchestration.SubTask\x1a'.ohc.orchestration.DelegateTaskResponseB9Z7github.com/onehumancorp/mono/srcs/proto;orchestrationpbb\x06proto3"

var (
	file_hub_proto_rawDescOnce sync.Once
	file_hub_proto_rawDescData []byte
)

func file_hub_proto_rawDescGZIP() []byte {
	file_hub_proto_rawDescOnce.Do(func() {
		file_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_proto_rawDesc), len(file_hub_proto_rawDesc)))
	})
	return file_hub_proto_rawDescData
}

var file_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_hub_proto_goTypes = []any{
	(*Agent)(nil),                                   // 0: ohc.orchestration.Agent
	(*Message)(nil),                                 // 1: ohc.orchestration.Message
	(*MeetingRoom)(nil),                             // 2: ohc.orchestration.MeetingRoom
	(*RegisterAgentRequest)(nil),                    // 3: ohc.orchestration.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),                   // 4: ohc.orchestration.RegisterAgentResponse
	(*OpenMeetingRequest)(nil),                      // 5: ohc.orchestration.OpenMeetingRequest
	(*PublishMessageRequest)(nil),                   // 6: ohc.orchestration.PublishMessageRequest
	(*PublishMessageResponse)(nil),                  // 7: ohc.orchestration.PublishMessageResponse
	(*DelegateTaskRequest)(nil),                     // 8: ohc.orchestration.DelegateTaskRequest
	(*DelegateTaskResponse)(nil),                    // 9: ohc.orchestration.DelegateTaskResponse
	(*SubTask)(nil),                                 // 10: ohc.orchestration.SubTask
	(*TokenEfficientContextSummarizationEvent)(nil), // 11: ohc.orchestration.TokenEfficientContextSummarizationEvent
	(*ToolParameterAutoCorrectionEvent)(nil),        // 12: ohc.orchestration.ToolParameterAutoCorrectionEvent
	(*StreamMessagesRequest)(nil),                   // 13: ohc.orchestration.StreamMessagesRequest
	(*ReasonRequest)(nil),                           // 14: ohc.orchestration.ReasonRequest
	(*ReasonResponse)(nil),                          // 15: ohc.orchestration.ReasonResponse
}
var file_hub_proto_depIdxs = []int32{
	1,  // 0: ohc.orchestration.MeetingRoom.transcript:type_name -> ohc.orchestration.Message
	0,  // 1: ohc.orchestration.RegisterAgentRequest.agent:type_name -> ohc.orchestration.Agent
	1,  // 2: ohc.orchestration.PublishMessageRequest.message:type_name -> ohc.orchestration.Message
	1,  // 3: ohc.orchestration.DelegateTaskRequest.task:type_name -> ohc.orchestration.Message
	3,  // 4: ohc.orchestration.HubService.RegisterAgent:input_type -> ohc.orchestration.RegisterAgentRequest
	5,  // 5: ohc.orchestration.HubService.OpenMeeting:input_type -> ohc.orchestration.OpenMeetingRequest
	6,  // 6: ohc.orchestration.HubService.Publish:input_type -> ohc.orchestration.PublishMessageRequest
	8,  // 7: ohc.orchestration.HubService.DelegateTask:input_type -> ohc.orchestration.DelegateTaskRequest
	13, // 8: ohc.orchestration.HubService.StreamMessages:input_type -> ohc.orchestration.StreamMessagesRequest
	14, // 9: ohc.orchestration.HubService.Reason:input_type -> ohc.orchestration.ReasonRequest
	10, // 10: ohc.orchestration.HubService.DelegateSubTask:input_type -> ohc.orchestration.SubTask
	4,  // 11: ohc.orchestration.HubService.RegisterAgent:output_type -> ohc.orchestration.RegisterAgentResponse
	2,  // 12: ohc.orchestration.HubService.OpenMeeting:output_type -> ohc.orchestration.MeetingRoom
	7,  // 13: ohc.orchestration.HubService.Publish:output_type -> ohc.orchestration.PublishMessageResponse
	9,  // 14: ohc.orchestration.HubService.DelegateTask:output_type -> ohc.orchestration.DelegateTaskResponse
	1,  // 15: ohc.orchestration.HubService.StreamMessages:output_type -> ohc.orchestration.Message
	15, // 16: ohc.orchestration.HubService.Reason:output_type -> ohc.orchestration.ReasonResponse
	9,  // 17: ohc.orchestration.HubService.DelegateSubTask:output_type -> ohc.orchestration.DelegateTaskResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hub_proto_init() }
func file_hub_proto_init() {
	if File_hub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_proto_rawDesc), len(file_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_proto_goTypes,
		DependencyIndexes: file_hub_proto_depIdxs,
		MessageInfos:      file_hub_proto_msgTypes,
	}.Build()
	File_hub_proto = out.File
	file_hub_proto_goTypes = nil
	file_hub_proto_depIdxs = nil
}
