// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: hub.proto

package orchestrationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubService_RegisterAgent_FullMethodName   = "/ohc.orchestration.HubService/RegisterAgent"
	HubService_OpenMeeting_FullMethodName     = "/ohc.orchestration.HubService/OpenMeeting"
	HubService_Publish_FullMethodName         = "/ohc.orchestration.HubService/Publish"
	HubService_DelegateTask_FullMethodName    = "/ohc.orchestration.HubService/DelegateTask"
	HubService_StreamMessages_FullMethodName  = "/ohc.orchestration.HubService/StreamMessages"
	HubService_Reason_FullMethodName          = "/ohc.orchestration.HubService/Reason"
	HubService_DelegateSubTask_FullMethodName = "/ohc.orchestration.HubService/DelegateSubTask"
)

// HubServiceClient is the client API for HubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubServiceClient interface {
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	OpenMeeting(ctx context.Context, in *OpenMeetingRequest, opts ...grpc.CallOption) (*MeetingRoom, error)
	Publish(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error)
	DelegateTask(ctx context.Context, in *DelegateTaskRequest, opts ...grpc.CallOption) (*DelegateTaskResponse, error)
	StreamMessages(ctx context.Context, in *StreamMessagesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error)
	Reason(ctx context.Context, in *ReasonRequest, opts ...grpc.CallOption) (*ReasonResponse, error)
	DelegateSubTask(ctx context.Context, in *SubTask, opts ...grpc.CallOption) (*DelegateTaskResponse, error)
}

type hubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubServiceClient(cc grpc.ClientConnInterface) HubServiceClient {
	return &hubServiceClient{cc}
}

func (c *hubServiceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, HubService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) OpenMeeting(ctx context.Context, in *OpenMeetingRequest, opts ...grpc.CallOption) (*MeetingRoom, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeetingRoom)
	err := c.cc.Invoke(ctx, HubService_OpenMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Publish(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishMessageResponse)
	err := c.cc.Invoke(ctx, HubService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) DelegateTask(ctx context.Context, in *DelegateTaskRequest, opts ...grpc.CallOption) (*DelegateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelegateTaskResponse)
	err := c.cc.Invoke(ctx, HubService_DelegateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) StreamMessages(ctx context.Context, in *StreamMessagesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[0], HubService_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessagesRequest, Message]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_StreamMessagesClient = grpc.ServerStreamingClient[Message]

func (c *hubServiceClient) Reason(ctx context.Context, in *ReasonRequest, opts ...grpc.CallOption) (*ReasonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReasonResponse)
	err := c.cc.Invoke(ctx, HubService_Reason_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) DelegateSubTask(ctx context.Context, in *SubTask, opts ...grpc.CallOption) (*DelegateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelegateTaskResponse)
	err := c.cc.Invoke(ctx, HubService_DelegateSubTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubServiceServer is the server API for HubService service.
// All implementations must embed UnimplementedHubServiceServer
// for forward compatibility.
type HubServiceServer interface {
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	OpenMeeting(context.Context, *OpenMeetingRequest) (*MeetingRoom, error)
	Publish(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error)
	DelegateTask(context.Context, *DelegateTaskRequest) (*DelegateTaskResponse, error)
	StreamMessages(*StreamMessagesRequest, grpc.ServerStreamingServer[Message]) error
	Reason(context.Context, *ReasonRequest) (*ReasonResponse, error)
	DelegateSubTask(context.Context, *SubTask) (*DelegateTaskResponse, error)
	mustEmbedUnimplementedHubServiceServer()
}

// UnimplementedHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubServiceServer struct{}

func (UnimplementedHubServiceServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedHubServiceServer) OpenMeeting(context.Context, *OpenMeetingRequest) (*MeetingRoom, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenMeeting not implemented")
}
func (UnimplementedHubServiceServer) Publish(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedHubServiceServer) DelegateTask(context.Context, *DelegateTaskRequest) (*DelegateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelegateTask not implemented")
}
func (UnimplementedHubServiceServer) StreamMessages(*StreamMessagesRequest, grpc.ServerStreamingServer[Message]) error {
	return status.Error(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedHubServiceServer) Reason(context.Context, *ReasonRequest) (*ReasonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reason not implemented")
}
func (UnimplementedHubServiceServer) DelegateSubTask(context.Context, *SubTask) (*DelegateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelegateSubTask not implemented")
}
func (UnimplementedHubServiceServer) mustEmbedUnimplementedHubServiceServer() {}
func (UnimplementedHubServiceServer) testEmbeddedByValue()                    {}

// UnsafeHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubServiceServer will
// result in compilation errors.
type UnsafeHubServiceServer interface {
	mustEmbedUnimplementedHubServiceServer()
}

func RegisterHubServiceServer(s grpc.ServiceRegistrar, srv HubServiceServer) {
	// If the following call panics, it indicates UnimplementedHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubService_ServiceDesc, srv)
}

func _HubService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_OpenMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).OpenMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_OpenMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).OpenMeeting(ctx, req.(*OpenMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Publish(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_DelegateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelegateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).DelegateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_DelegateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).DelegateTask(ctx, req.(*DelegateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).StreamMessages(m, &grpc.GenericServerStream[StreamMessagesRequest, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_StreamMessagesServer = grpc.ServerStreamingServer[Message]

func _HubService_Reason_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReasonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Reason(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Reason_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Reason(ctx, req.(*ReasonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_DelegateSubTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).DelegateSubTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_DelegateSubTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).DelegateSubTask(ctx, req.(*SubTask))
	}
	return interceptor(ctx, in, info, handler)
}

// HubService_ServiceDesc is the grpc.ServiceDesc for HubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ohc.orchestration.HubService",
	HandlerType: (*HubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _HubService_RegisterAgent_Handler,
		},
		{
			MethodName: "OpenMeeting",
			Handler:    _HubService_OpenMeeting_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _HubService_Publish_Handler,
		},
		{
			MethodName: "DelegateTask",
			Handler:    _HubService_DelegateTask_Handler,
		},
		{
			MethodName: "Reason",
			Handler:    _HubService_Reason_Handler,
		},
		{
			MethodName: "DelegateSubTask",
			Handler:    _HubService_DelegateSubTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _HubService_StreamMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hub.proto",
}
