import os
import re

meanings = {
    # dashboard/server.go
    "Server": "encapsulates the HTTP routing logic, REST middleware, and cross-module state required to expose the One Human Corp dashboard to the human CEO.",
    "Settings": "represents the global platform configuration, dictating UI themes, agent behavioral defaults, and connected integration states.",
    "ApprovalStatus": "represents the strict human-in-the-loop lifecycle state for intercepting high-risk agent actions via the Guardian gate.",
    "ApprovalStatusPending": "indicates an action is explicitly blocked, awaiting human manager review via the UI dashboard.",
    "ApprovalStatusApproved": "indicates a high-risk action has been successfully authorized by a human and will proceed to execution.",
    "ApprovalStatusRejected": "indicates a high-risk action was explicitly denied by a human manager and subsequently aborted.",
    "ApprovalRequest": "is generated by the Guardian agent when it intercepts a high-risk operational intent requiring explicit human sign-off.",
    "HandoffPackage": "carries the structured execution context, artifact history, and reasoning tree an agent sends when escalating an unresolvable task to a human.",
    "AgentIdentity": "represents the short-lived SPIFFE SVID certificate issued to a Kubernetes agent workload, enforcing zero-trust mTLS access.",
    "SkillPackRole": "pairs an agent role archetype with an override base prompt to dynamically modify behavior without container rebuilds.",
    "SkillPack": "is an importable, hot-pluggable module containing external MCP tools, specific prompts, and domain workflows.",
    "OrgSnapshot": "is an immutable point-in-time metadata record of an organization's state, enabling deterministic disaster recovery and rollback.",
    "MarketplaceItem": "describes a published artifact (agent template, skill, or workflow) available for dynamic import into the local runtime.",
    "AnalyticsSummary": "surfaces real-time token velocity, cost estimates, and active agent metrics directly to the executive React frontend.",
    "MCPTool": "represents a registered Tool schema in the Model Context Protocol gateway, defining the execution contract for external SaaS invocations.",
    "DomainInfo": "describes a supported organizational domain template providing a pre-configured role hierarchy (e.g., 'Software Company').",
    "TrustAgreementStatus": "represents the lifecycle phase of a federated trust agreement, governing encrypted cross-cluster agent communication.",
    "TrustStatusPending": "indicates a proposed B2B federation link currently awaiting cryptographic SPIFFE handshake verification.",
    "TrustStatusActive": "indicates a fully verified B2B federation link, permitting bidirectional cross-org agent collaboration.",
    "TrustStatusRevoked": "indicates a explicitly terminated B2B federation link, instantly nullifying all associated access tokens.",
    "TrustAgreement": "establishes a cryptographically verified, federated trust relationship between two distinct One Human Corp deployments using SPIFFE-federated JWTs.",
    "IncidentSeverity": "classifies the blast radius of an operational anomaly to determine the SRE agent's escalation path.",
    "SeverityP0": "represents a catastrophic platform failure requiring immediate, synchronous human and SRE agent intervention.",
    "SeverityP1": "represents a severe degradation of a critical business path, triggering immediate automated remediation attempts.",
    "SeverityP2": "represents a localized, non-critical issue that will be asynchronously triaged by SRE agents.",
    "IncidentStatus": "reflects the current automated investigation and remediation lifecycle state of an operational anomaly.",
    "IncidentStatusInvestigating": "indicates an SRE agent is actively analyzing logs, traces, and metrics to identify the root cause of an anomaly.",
    "IncidentStatusProposed": "indicates an SRE agent has formulated a remediation plan and is awaiting human execution approval.",
    "IncidentStatusResolved": "indicates the anomaly has been successfully mitigated and verified by automated checks.",
    "Incident": "represents a distinct operational event requiring SRE attention, encapsulating its timeline, severity context, and remediation history.",
    "ComputeProfile": "defines the strict hardware constraints (CPU, Memory) and affinity rules for a specific agent role, ensuring optimal Kubernetes pod scheduling.",
    "ClusterStatus": "reflects the real-time node health, resource capacity, and latency metrics of a remote Kubernetes region for workload placement.",
    "BudgetAlert": "defines a proactive spending threshold with associated notification circuit-breaker behaviors to prevent runaway token costs.",
    "PipelineStatus": "reflects the current lifecycle phase of an autonomous CI/CD implementation pipeline driven by agent collaboration.",
    "PipelineStatusPending": "indicates an autonomous pipeline has been created but has not yet commenced code generation.",
    "PipelineStatusImplementing": "indicates Software Engineer agents are actively iterating on code to satisfy the generated feature specification.",
    "PipelineStatusTesting": "indicates QA agents are actively executing and verifying the implementation against the automated test suites.",
    "PipelineStatusStaging": "indicates the feature has passed automated checks and is deployed to an ephemeral environment for final human review.",
    "PipelineStatusPromoted": "indicates the feature has been successfully merged and deployed to the production environment.",
    "PipelineStatusFailed": "indicates the pipeline encountered an unrecoverable compilation error or test failure requiring manual intervention.",
    "Pipeline": "represents an autonomous, end-to-end implementation workflow, tracking a feature's progression from approved spec to a deployed artifact.",

    # billing/tracker.go
    "Price": "represents the explicit input and output cost rates per million tokens for a specific large language model inference engine.",
    "DefaultCatalog": "provides a comprehensive, read-only dictionary of known LLM inference prices, serving as the foundational reference for cost estimation.",
    "Usage": "models a single, discrete inference event's token consumption and computes its associated USD cost based on the active pricing catalog.",
    "AgentSummary": "provides an aggregated view of total cost and token usage attributable to an individual AI agent across all its active execution sessions.",
    "Summary": "aggregates the total infrastructure spend, overall token count, and per-agent metrics for a specific organization.",
    "trackerShard": "isolates token tracking data for specific organizations to drastically reduce global mutex contention under high-throughput event ingestion.",
    "Tracker": "calculates and safely persists LLM token consumption and associated costs across highly concurrent operations using an internal sharded read-write mutex.",
    "NewTracker": "constructs and returns a thread-safe Tracker instance configured with the specified model pricing catalog and initializes its internal sharding logic.",
    "Track": "calculates the USD cost for a given token consumption event and safely appends it to the internal sharded memory store.",

    # auth/store.go
    "User": "represents a persistent user account with encrypted credentials and role-based permissions within the platform.",
    "UserPublic": "represents the sanitized, non-sensitive profile of a user suitable for external API consumption.",
    "Role": "defines an operational role with an associated array of access permissions for Role-Based Access Control (RBAC).",
    "Store": "manages secure, thread-safe persistence for user accounts, credentials, and roles, using mutexes for concurrent access.",

    # auth/jwt.go
    "jwtHeader": "represents the standard JSON Web Token header containing the signing algorithm and token type.",
    "Claims": "embeds the standard JWT Registered Claims and adds custom One Human Corp properties like user ID and assigned roles.",
    "GenerateToken": "creates a cryptographically signed JSON Web Token utilizing the HMAC SHA-256 (HS256) signature algorithm.",
    "ValidateToken": "parses and verifies a JSON Web Token string, enforcing expiration checks and valid signature algorithms.",

    # orchestration/service.go
    "Agent": "represents an autonomous AI actor registered in the orchestration Hub, tracking its identity, role, and current state.",
    "Message": "represents a discrete packet of communication between agents within a meeting room, containing the content and sender identity.",
    "MeetingRoom": "provides a thread-safe, isolated collaborative space where multiple agents can exchange messages and context.",
    "Hub": "acts as the central, thread-safe asynchronous message broker and state registry for all active agents and meeting rooms.",
    "HubServiceServer": "implements the gRPC interface for the orchestration Hub, facilitating remote agent registration and message streaming.",

    # domain/organization.go
    "Member": "represents a distinct individual (human or AI agent) assigned to a specific role within the organizational hierarchy.",
    "RoleProfile": "defines the operational responsibilities, expected skill set, and default tools for a specific archetype within the organization.",
    "Organization": "represents the top-level structural entity, maintaining the hierarchy of members, active roles, and cross-team workflows.",

    # frontend/server/server.go
    "New": "constructs and initializes a new instance of the core service component, wiring together necessary dependencies like static directories, proxy endpoints, or storage backends.",
    "Handler": "returns a multiplexed HTTP handler configured with the necessary API routes and static asset serving capabilities for the module."
}

def process_go_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    modified = False
    new_lines = []

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Check if line is // Summary:
        if stripped.startswith('// Summary:'):
            # Extract plain text
            text = stripped[len('// Summary:'):].strip()

            # Find next actual declaration to extract the precise symbol name
            symbol = ""
            for j in range(i + 1, len(lines)):
                nl = lines[j].strip()
                if not nl.startswith('//') and nl != "":
                    # match type/var/const/func
                    m_decl = re.match(r'^(type|var|const|func)\s+([A-Za-z0-9_]+)', nl)
                    m_meth = re.match(r'^func\s+\([^\)]+\)\s+([A-Za-z0-9_]+)', nl)
                    m_ident = re.match(r'^([A-Za-z0-9_]+)\s*(?:[A-Za-z0-9_.]+\s*)?=', nl)
                    m_just = re.match(r'^([A-Za-z0-9_]+)', nl)

                    if m_decl:
                        symbol = m_decl.group(2)
                        break
                    elif m_meth:
                        symbol = m_meth.group(1)
                        break
                    elif m_ident:
                        symbol = m_ident.group(1)
                        break
                    elif m_just and nl != "}":
                        symbol = m_just.group(1)
                        break
                    break

            indent = line[:line.find('//')]

            # Use meaning if available
            if symbol and symbol in meanings:
                new_line = f"{indent}// {symbol} {meanings[symbol]}\n"
            else:
                # If we don't have a specific meaning, format it correctly
                # e.g. "Defines the Settings type." -> "Settings defines the Settings type."
                if symbol:
                    if text.startswith(symbol):
                        new_line = f"{indent}// {text}\n"
                    else:
                        words = text.split()
                        if words and words[0] in ["Defines", "Represents", "Provides", "Is", "Returns", "Sets", "Gets", "Creates", "Updates", "Deletes", "Handles", "Validates", "Extracts", "Registers", "Parses", "Writes"]:
                            text = text[0].lower() + text[1:]
                        new_line = f"{indent}// {symbol} {text}\n"
                else:
                    new_line = f"{indent}// {text}\n"

            new_lines.append(new_line)
            modified = True
            i += 1
        else:
            new_lines.append(line)
            i += 1

    if modified:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.writelines(new_lines)

def main():
    for root, dirs, files in os.walk('.'):
        if 'node_modules' in root or '.git' in root or 'bazel-' in root:
            continue
        for file in files:
            if file.endswith('.go'):
                process_go_file(os.path.join(root, file))

if __name__ == "__main__":
    main()
