package main

import (
	"fmt"
	"strings"
)

func main() {
    // There is an interceptor test file: `auth_interceptor_test.go`
    // Wait, the memory states:
    // "When processing high-frequency gRPC calls, such as SPIFFE ID extraction in interceptors, avoid O(N) memory allocations like strings.Split and unbounded caching mechanisms like sync.Map that cause memory leaks. Prefer zero-allocation or low-allocation string manipulations like strings.Count, strings.IndexByte, and strings.TrimPrefix."
    // AND
    // "When implementing zero-allocation string parsing (e.g., to replace strings.Split) for security-sensitive identifiers like SPIFFE IDs, ensure the parser explicitly counts the total number of segments, even those exceeding the expected length, to accurately enforce strict length constraints and prevent path-based spoofing attacks."

    // In `auth_interceptor.go`:
    // It DOES replace strings.Split.
    // BUT what if `slashCount := strings.Count(rest, "/")` fails to catch `..`? No, if it's `..`, the slash count still matches. If it's `../`, then the slash count increases.

    // So if the spiffeID is `spiffe://onehumancorp.io/org-1/attacker%2f..%2fagent-1`
    // `strings.Count(rest, "/")` is 1. (because "%2f" is not a slash).
    // `agentID` is `attacker%2f..%2fagent-1`.

    // Could it be that `strings.Count(rest, "/")` counts slashes but we need to ensure there are no uncounted segments? Wait, how can there be uncounted segments if segments are strictly separated by slashes?

    // Wait, what if the memory prompt was referring to the code we NEED to implement?
    // Let's re-read the code we found.
    // ⚡ BOLT: [Redundant SPIFFE SVID X.509 certificate validation on internal gRPC inter-agent calls] - Randomized Selection from Top 5
	// Extracted zero-allocation string manipulations to parse SPIFFE IDs strictly without triggering O(N) memory allocations via strings.Split

    // This is the code that is CURRENTLY in auth_interceptor.go. This code was generated by Bolt to fix memory allocations.
    // So the vulnerability is the current implementation using `strings.Count`.

    // How to "explicitly count the total number of segments, even those exceeding the expected length"?
    // The problem is that if `rest` contains `../` or `%2f`, they might bypass checks. But if it contains `../`, `strings.Count` catches the extra slash!
    // What if `rest` has a query parameter? `spiffe://onehumancorp.io/org-1/agent-1?query=1/2` -> `slashCount` = 2, rejected!
    // But `spiffe://onehumancorp.io/org-1/agent-1?query=1` -> `slashCount` = 1, `agentID` = `agent-1?query=1`.

    // To explicitly count segments, we can iterate over the string and check segment lengths:
    // E.g.
    segmentCount := 1
    for i := 0; i < len("a/b"); i++ {
        if "a/b"[i] == '/' {
            segmentCount++
        }
    }
    fmt.Println(segmentCount)
    // "even those exceeding the expected length" means maybe we have to limit the search length?
    // E.g. if we expect 3 segments, we stop looking after 3 segments? No, if we stop looking, we don't count the ones exceeding.

    // Wait. In `auth_interceptor.go`, the code reads:
    // slashCount := strings.Count(rest, "/")
    // if slashCount != 1 { return error }
    // This perfectly counts slashes exactly.
    // So what is the flaw?
}
