apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: OHC_REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379"
{{- if .Values.postgresql.enabled }}
            - name: OHC_POSTGRES_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: OHC_POSTGRES_PORT
              value: "5432"
            - name: OHC_POSTGRES_DB
              value: "{{ .Values.postgresql.auth.database }}"
            - name: OHC_POSTGRES_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: OHC_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgres-password
{{- end }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}