package dashboard

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/onehumancorp/mono/srcs/backend/agents"
	"github.com/onehumancorp/mono/srcs/backend/auth"
	"github.com/onehumancorp/mono/srcs/backend/billing"
	"github.com/onehumancorp/mono/srcs/backend/domain"
	"github.com/onehumancorp/mono/srcs/backend/integrations"
	"github.com/onehumancorp/mono/srcs/backend/interop"
	"github.com/onehumancorp/mono/srcs/backend/orchestration"
	"github.com/onehumancorp/mono/srcs/backend/telemetry"
)

// Server encapsulates the HTTP routing logic, REST middleware, and cross-module state required to expose the One Human Corp dashboard to the human CEO.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type Server struct {
	mu                    sync.RWMutex
	org                   domain.Organization
	// ⚡ BOLT: [high-allocation hashing or mapping for agent roles] - Randomized Selection from Top 5
	roleProfileCache      map[string]domain.RoleProfile
	hub                   *orchestration.Hub
	tracker               *billing.Tracker
	approvals             []ApprovalRequest
	handoffs              []HandoffPackage
	skills                []SkillPack
	snapshots             []OrgSnapshot
	integReg              *integrations.Registry
	trustAgreements       []TrustAgreement
	incidents             []Incident
	computeProfiles       []ComputeProfile
	budgetAlerts          []BudgetAlert
	pipelines             []Pipeline
	authStore             *auth.Store
	authHandlers          *auth.Handlers
	settings              Settings
	agentProviderRegistry *agents.Registry
	dynamicMCPTools       []MCPTool
	rateLimitStates       map[string]*RateLimitState
}

// RateLimitState functionality.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type RateLimitState struct {
	Failures    int
	LastFailure time.Time
	Backoff     time.Duration
}

// Settings represents the global platform configuration, dictating UI themes, agent behavioral defaults, and connected integration states.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type Settings struct {
	MinimaxAPIKey string `json:"minimaxApiKey"`
	Theme         string `json:"theme,omitempty"`
}

type statusCount struct {
	Status orchestration.Status `json:"status"`
	Count  int                  `json:"count"`
}

type dashboardSnapshot struct {
	Organization domain.Organization         `json:"organization"`
	Meetings     []*orchestration.MeetingRoom `json:"meetings"`
	Costs        billing.Summary             `json:"costs"`
	Agents       []orchestration.Agent       `json:"agents"`
	Statuses     []statusCount               `json:"statuses"`
	UpdatedAt    time.Time                   `json:"updatedAt"`
}

type seedRequest struct {
	Scenario string `json:"scenario"`
}

// hireRequest carries agent creation parameters.
type hireRequest struct {
	Name         string `json:"name"`
	Role         string `json:"role"`
	Model        string `json:"model,omitempty"`
	ProviderType string `json:"providerType,omitempty"`
	Region       string `json:"region,omitempty"`
}

// fireRequest carries the ID of the agent to remove.
type fireRequest struct {
	AgentID string `json:"agentId"`
}

// delegateRequest carries parameters for delegating a task.
type delegateRequest struct {
	FromAgentID string `json:"fromAgentId"`
	ToAgentID   string `json:"toAgentId"`
	MeetingID   string `json:"meetingId,omitempty"`
	Content     string `json:"content"`
}

// ── Approval / Confidence Gating ─────────────────────────────────────────────

// ApprovalStatus represents the strict human-in-the-loop lifecycle state for intercepting high-risk agent actions via the Guardian gate.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type ApprovalStatus string

const (
	// ApprovalStatusPending indicates an action is explicitly blocked, awaiting human manager review via the UI dashboard.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	ApprovalStatusPending ApprovalStatus = "PENDING"
	// ApprovalStatusApproved indicates a high-risk action has been successfully authorized by a human and will proceed to execution.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	ApprovalStatusApproved ApprovalStatus = "APPROVED"
	// ApprovalStatusRejected indicates a high-risk action was explicitly denied by a human manager and subsequently aborted.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	ApprovalStatusRejected ApprovalStatus = "REJECTED"
)

// ApprovalRequest is generated by the Guardian agent when it intercepts a high-risk operational intent requiring explicit human sign-off.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type ApprovalRequest struct {
	ID               string         `json:"id"`
	AgentID          string         `json:"agentId"`
	Action           string         `json:"action"`
	Reason           string         `json:"reason"`
	EstimatedCostUSD float64        `json:"estimatedCostUsd"`
	RiskLevel        string         `json:"riskLevel"` // low | medium | high | critical
	Status           ApprovalStatus `json:"status"`
	CreatedAt        time.Time      `json:"createdAt"`
	DecidedAt        *time.Time     `json:"decidedAt,omitempty"`
	DecidedBy        string         `json:"decidedBy,omitempty"`
}

type approvalCreateRequest struct {
	AgentID          string  `json:"agentId"`
	Action           string  `json:"action"`
	Reason           string  `json:"reason"`
	EstimatedCostUSD float64 `json:"estimatedCostUsd"`
	RiskLevel        string  `json:"riskLevel"`
}

type approvalDecideRequest struct {
	ApprovalID string `json:"approvalId"`
	Decision   string `json:"decision"` // approve | reject
	DecidedBy  string `json:"decidedBy"`
}

// ── Warm Handoff ──────────────────────────────────────────────────────────────

// HandoffPackage carries the structured execution context, artifact history, and reasoning tree an agent sends when escalating an unresolvable task to a human.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type HandoffPackage struct {
	ID                string    `json:"id"`
	FromAgentID       string    `json:"fromAgentId"`
	ToHumanRole       string    `json:"toHumanRole"`
	Intent            string    `json:"intent"`
	FailedAttempts    int       `json:"failedAttempts"`
	CurrentState      string    `json:"currentState"`
	VisualGroundTruth string    `json:"visualGroundTruth,omitempty"`
	Status            string    `json:"status"` // pending | acknowledged | resolved
	CreatedAt         time.Time `json:"createdAt"`
}

type handoffCreateRequest struct {
	FromAgentID       string `json:"fromAgentId"`
	ToHumanRole       string `json:"toHumanRole"`
	Intent            string `json:"intent"`
	FailedAttempts    int    `json:"failedAttempts"`
	CurrentState      string `json:"currentState"`
	VisualGroundTruth string `json:"visualGroundTruth,omitempty"`
}

// ── Agent Identity (SPIFFE/SPIRE abstraction) ─────────────────────────────────

// AgentIdentity represents the short-lived SPIFFE SVID certificate issued to a Kubernetes agent workload, enforcing zero-trust mTLS access.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type AgentIdentity struct {
	AgentID     string    `json:"agentId"`
	SVID        string    `json:"svid"`
	TrustDomain string    `json:"trustDomain"`
	IssuedAt    time.Time `json:"issuedAt"`
	ExpiresAt   time.Time `json:"expiresAt"`
}

// ── Extensible Skill Import Framework ────────────────────────────────────────

// SkillPackRole pairs an agent role archetype with an override base prompt to dynamically modify behavior without container rebuilds.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type SkillPackRole struct {
	Role       string `json:"role"`
	BasePrompt string `json:"basePrompt"`
}

// SkillPack is an importable, hot-pluggable module containing external MCP tools, specific prompts, and domain workflows.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type SkillPack struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Domain      string          `json:"domain"`
	Description string          `json:"description"`
	Source      string          `json:"source"` // builtin | custom | marketplace
	Author      string          `json:"author,omitempty"`
	Roles       []SkillPackRole `json:"roles"`
	ImportedAt  time.Time       `json:"importedAt"`
}

type skillImportRequest struct {
	Name        string          `json:"name"`
	Domain      string          `json:"domain"`
	Description string          `json:"description"`
	Source      string          `json:"source"`
	Author      string          `json:"author,omitempty"`
	Roles       []SkillPackRole `json:"roles"`
}

// ── Org Snapshot & Recovery ───────────────────────────────────────────────────

// OrgSnapshot is an immutable point-in-time metadata record of an organization's state, enabling deterministic disaster recovery and rollback.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type OrgSnapshot struct {
	ID           string    `json:"id"`
	Label        string    `json:"label"`
	OrgID        string    `json:"orgId"`
	OrgName      string    `json:"orgName"`
	Domain       string    `json:"domain"`
	AgentCount   int       `json:"agentCount"`
	MeetingCount int       `json:"meetingCount"`
	MessageCount int       `json:"messageCount"`
	CreatedAt    time.Time `json:"createdAt"`
}

type snapshotCreateRequest struct {
	Label string `json:"label"`
}

type snapshotRestoreRequest struct {
	SnapshotID string `json:"snapshotId"`
}

// ── Marketplace ───────────────────────────────────────────────────────────────

// MarketplaceItem describes a published artifact (agent template, skill, or workflow) available for dynamic import into the local runtime.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type MarketplaceItem struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Type        string   `json:"type"` // agent | domain | skill_pack | tool
	Author      string   `json:"author"`
	Description string   `json:"description"`
	Downloads   int      `json:"downloads"`
	Rating      float64  `json:"rating"`
	Tags        []string `json:"tags"`
}

// ── Real-time Analytics ───────────────────────────────────────────────────────

// AnalyticsSummary surfaces real-time token velocity, cost estimates, and active agent metrics directly to the executive React frontend.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type AnalyticsSummary struct {
	HumanAgentRatio     float64 `json:"humanAgentRatio"`
	TotalAgents         int     `json:"totalAgents"`
	TotalHumans         int     `json:"totalHumans"`
	AuditFidelityPct    float64 `json:"auditFidelityPct"`
	ResumptionLatencyMS int     `json:"resumptionLatencyMs"`
	PendingApprovals    int     `json:"pendingApprovals"`
	ActiveHandoffs      int     `json:"activeHandoffs"`
	TokenVelocity       int64   `json:"tokenVelocity"`
}

// MCPTool represents a registered Tool schema in the Model Context Protocol gateway, defining the execution contract for external SaaS invocations.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type MCPTool struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Category    string `json:"category"`
	Status      string `json:"status"`
}

// DomainInfo describes a supported organizational domain template providing a pre-configured role hierarchy (e.g., 'Software Company').
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type DomainInfo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

var availableDomains = []DomainInfo{
	{ID: "software_company", Name: "Software Company", Description: "Full-stack engineering org: CEO, Director, PM, SWEs, QA, Security, Designer, Marketing."},
	{ID: "digital_marketing_agency", Name: "Digital Marketing Agency", Description: "Full-service agency: CEO, Marketing Director, Growth, Content, SEO, Paid Media, Analytics, Designer."},
	{ID: "accounting_firm", Name: "Accounting Firm", Description: "Financial services firm: CEO, CFO, Bookkeepers, Tax, Audit, Payroll."},
}

var defaultMcpTools = []MCPTool{
	{ID: "git-mcp", Name: "Git", Description: "Source control operations: clone, commit, pull-request, review via GitHub or Gitea.", Category: "code", Status: "available"},
	{ID: "jira-mcp", Name: "Jira / Plane", Description: "Task and issue tracking: create tickets, update status, list sprint items.", Category: "project_management", Status: "available"},
	{ID: "linear-mcp", Name: "Linear", Description: "Modern issue tracking: manage issues, cycles, and roadmaps for high-velocity teams.", Category: "project_management", Status: "available"},
	{ID: "figma-mcp", Name: "Figma", Description: "Design file access: read wireframes, export assets, inspect component specs.", Category: "design", Status: "available"},
	{ID: "aws-mcp", Name: "AWS", Description: "Cloud infrastructure: provision EC2 instances, manage S3, deploy Lambda functions.", Category: "infrastructure", Status: "available"},
	{ID: "gcp-mcp", Name: "Google Cloud Platform", Description: "Cloud infrastructure: manage GCE instances, Cloud Storage, Cloud Run, and GKE clusters.", Category: "infrastructure", Status: "available"},
	{ID: "azure-mcp", Name: "Microsoft Azure", Description: "Cloud infrastructure: provision VMs, manage Azure Blob Storage, deploy Azure Functions.", Category: "infrastructure", Status: "available"},
	{ID: "kubernetes-mcp", Name: "Kubernetes", Description: "Container orchestration: deploy workloads, scale pods, inspect cluster health.", Category: "infrastructure", Status: "available"},
	{ID: "slack-mcp", Name: "Slack / Mattermost", Description: "Human-in-the-loop approval: send HITL notifications, await human manager sign-off.", Category: "communication", Status: "available"},
	{ID: "telegram-mcp", Name: "Telegram", Description: "Agent messaging via Telegram bots: send notifications and collect HITL responses.", Category: "communication", Status: "available"},
	{ID: "teams-mcp", Name: "Microsoft Teams", Description: "Agent messaging via Teams webhooks: post updates and await approval from human managers.", Category: "communication", Status: "available"},
	{ID: "postgres-mcp", Name: "PostgreSQL", Description: "Database operations: run queries, manage schema, inspect table data.", Category: "database", Status: "available"},
	{ID: "mysql-mcp", Name: "MySQL", Description: "Database operations: run queries, manage schema, and inspect MySQL or MariaDB table data.", Category: "database", Status: "available"},
	{ID: "redis-mcp", Name: "Redis", Description: "In-memory data store: manage keys, queues, pub/sub channels, and caching layers.", Category: "database", Status: "available"},
	{ID: "opentelemetry-mcp", Name: "OpenTelemetry", Description: "Observability: push metrics and traces to Grafana / OpenObserve dashboards.", Category: "observability", Status: "available"},
	{ID: "datadog-mcp", Name: "Datadog", Description: "Monitoring and APM: query metrics, manage monitors, and inspect distributed traces.", Category: "observability", Status: "available"},
	{ID: "sentry-mcp", Name: "Sentry", Description: "Error tracking: capture exceptions, triage issues, and link errors to code changes.", Category: "observability", Status: "available"},
	{ID: "github-actions-mcp", Name: "GitHub Actions", Description: "CI/CD pipelines: trigger workflow runs, inspect job logs, and manage deployment environments.", Category: "cicd", Status: "available"},
	{ID: "notion-mcp", Name: "Notion", Description: "Knowledge base: read and write pages, manage databases, and retrieve structured documentation.", Category: "knowledge", Status: "available"},
	{ID: "spire-mcp", Name: "SPIFFE/SPIRE", Description: "Identity management: issue and rotate SVID certificates for agent workloads.", Category: "identity", Status: "available"},
}

var statusOrder = []orchestration.Status{
	orchestration.StatusActive,
	orchestration.StatusBlocked,
	orchestration.StatusIdle,
	orchestration.StatusInMeeting,
}

// NewServer initializes a new Dashboard HTTP handler that routes all API and frontend requests.
//
//   - org: domain.Organization; The base organizational structure.
//   - hub: *orchestration.Hub; The agent communication and meeting room registry.
//   - tracker: *billing.Tracker; The cost and token tracking engine.
//
// Accepts parameters: org domain.Organization, hub *orchestration.Hub, tracker *billing.Tracker, authStore ...*auth.Store (No Constraints).
// Returns http.Handler.
// Produces no errors.
// Has no side effects.
func NewServer(org domain.Organization, hub *orchestration.Hub, tracker *billing.Tracker, authStore ...*auth.Store) http.Handler {
	var store *auth.Store
	if len(authStore) > 0 && authStore[0] != nil {
		store = authStore[0]
	} else {
		store = auth.NewStore()
	}

	rpc := make(map[string]domain.RoleProfile, len(org.RoleProfiles))
	for _, rp := range org.RoleProfiles {
		rpc[string(rp.Role)] = rp
	}

	server := &Server{
		org:                   org,
		roleProfileCache:      rpc,
		hub:                   hub,
		tracker:               tracker,
		approvals:             []ApprovalRequest{},
		handoffs:              []HandoffPackage{},
		skills:                defaultSkillPacks(),
		snapshots:             []OrgSnapshot{},
		integReg:              integrations.NewRegistry(),
		trustAgreements:       []TrustAgreement{},
		incidents:             []Incident{},
		computeProfiles:       []ComputeProfile{},
		budgetAlerts:          []BudgetAlert{},
		pipelines:             []Pipeline{},
		authStore:             store,
		authHandlers:          auth.NewHandlers(store),
		agentProviderRegistry: agents.DefaultRegistry(),
		dynamicMCPTools:       append([]MCPTool(nil), defaultMcpTools...),
		rateLimitStates:       make(map[string]*RateLimitState),
	}
	// Load Minimax API key from environment on startup.
	if key := os.Getenv("MINIMAX_API_KEY"); key != "" {
		hub.SetMinimaxAPIKey(key)
		server.settings.MinimaxAPIKey = key
		if err := server.agentProviderRegistry.Authenticate(agents.ProviderTypeOpenClaw, agents.Credentials{APIKey: key}); err != nil {
			slog.Warn("failed to authenticate OpenClaw provider with MINIMAX_API_KEY", "error", err)
		}
	}
	// Pre-authenticate providers from environment variables so the platform
	// forwards credentials to freshly hired agents without requiring manual auth.
	if key := os.Getenv("ANTHROPIC_API_KEY"); key != "" {
		_ = server.agentProviderRegistry.Authenticate(agents.ProviderTypeClaude, agents.Credentials{APIKey: key})
	}
	if key := os.Getenv("GEMINI_API_KEY"); key != "" {
		_ = server.agentProviderRegistry.Authenticate(agents.ProviderTypeGemini, agents.Credentials{APIKey: key})
	}
	if key := os.Getenv("OPENAI_API_KEY"); key != "" {
		_ = server.agentProviderRegistry.Authenticate(agents.ProviderTypeOpenCode, agents.Credentials{APIKey: key})
	}
	mux := http.NewServeMux()
	mux.HandleFunc("/", server.handleIndex)
	mux.HandleFunc("/api/dashboard", server.handleDashboard)
	mux.HandleFunc("/api/org", server.handleOrg)
	mux.HandleFunc("/api/meetings", server.handleMeetings)
	mux.HandleFunc("/api/costs", server.handleCosts)
	mux.HandleFunc("/api/messages", server.handleSendMessage)
	mux.HandleFunc("/api/agents/hire", server.handleHireAgent)
	mux.HandleFunc("/api/agents/fire", server.handleFireAgent)
	mux.HandleFunc("/api/agents/delegate", server.handleDelegateTask)
	// Agent provider management
	mux.HandleFunc("/api/agents/providers", server.handleAgentProviders)
	mux.HandleFunc("/api/agents/providers/auth", server.handleAgentProviderAuth)
	mux.HandleFunc("/api/domains", server.handleDomains)
	mux.HandleFunc("/api/mcp/tools", server.handleMCPTools)
	mux.HandleFunc("/api/mcp/tools/register", server.handleMCPRegister)
	mux.HandleFunc("/api/mcp/tools/invoke", server.handleMCPInvoke)
	mux.HandleFunc("/api/dev/seed", server.handleDevSeed)
	mux.HandleFunc("/api/settings", server.handleSettings)
	// Phase 2 – Confidence Gating / Guardian Agent
	mux.HandleFunc("/api/approvals", server.handleApprovals)
	mux.HandleFunc("/api/approvals/request", server.handleApprovalRequest)
	mux.HandleFunc("/api/approvals/decide", server.handleApprovalDecide)
	// Phase 2 – Warm Handoff
	mux.HandleFunc("/api/handoffs", server.handleHandoffs)
	mux.HandleFunc("/api/handoffs/resolve", server.handleHandoffResolve)
	// Phase 2 – Unified Identity Management (SPIFFE/SPIRE)
	mux.HandleFunc("/api/identities", server.handleIdentities)
	// Phase 2 – Extensible Skill Import Framework
	mux.HandleFunc("/api/skills", server.handleSkills)
	mux.HandleFunc("/api/skills/import", server.handleSkillImport)
	// Phase 4 – Org Snapshot & Recovery
	mux.HandleFunc("/api/snapshots", server.handleSnapshots)
	mux.HandleFunc("/api/snapshots/create", server.handleSnapshotCreate)
	mux.HandleFunc("/api/snapshots/restore", server.handleSnapshotRestore)
	// Phase 4 – Community Marketplace
	mux.HandleFunc("/api/marketplace", server.handleMarketplace)
	// Phase 4 – Real-time Analytics
	mux.HandleFunc("/api/analytics", server.handleAnalytics)
	// Phase 2 – External Integrations (chat, git, issues)
	mux.HandleFunc("/api/integrations", server.handleIntegrations)
	mux.HandleFunc("/api/integrations/connect", server.handleIntegrationConnect)
	mux.HandleFunc("/api/integrations/disconnect", server.handleIntegrationDisconnect)
	mux.HandleFunc("/api/integrations/chat/messages", server.handleChatMessages)
	mux.HandleFunc("/api/integrations/chat/send", server.handleChatSend)
	mux.HandleFunc("/api/integrations/chat/test", server.handleChatTest)
	mux.HandleFunc("/api/integrations/git/prs", server.handlePullRequests)
	mux.HandleFunc("/api/integrations/git/pr/create", server.handlePRCreate)
	mux.HandleFunc("/api/integrations/git/pr/merge", server.handlePRMerge)
	mux.HandleFunc("/api/integrations/git/pr/close", server.handlePRClose)
	mux.HandleFunc("/api/integrations/issues", server.handleIssues)
	mux.HandleFunc("/api/integrations/issues/create", server.handleIssueCreate)
	mux.HandleFunc("/api/integrations/issues/status", server.handleIssueUpdateStatus)
	mux.HandleFunc("/api/integrations/issues/assign", server.handleIssueAssign)
	// Phase 5 – B2B Cross-Org Collaboration
	mux.HandleFunc("/api/b2b/agreements", server.handleB2BAgreements)
	mux.HandleFunc("/api/b2b/handshake", server.handleB2BHandshake)
	mux.HandleFunc("/api/b2b/revoke", server.handleB2BRevoke)
	// Phase 5 – Autonomous SRE / Incident Management
	mux.HandleFunc("/api/v1/scale", server.handleScale)
	mux.HandleFunc("/api/v1/scale/stream", server.handleScaleStream)
	mux.HandleFunc("/api/incidents", server.handleIncidents)
	mux.HandleFunc("/api/incidents/status", server.handleIncidentStatus)
	// Phase 5 – Compute Optimisation / Hardware-Aware Scheduling
	mux.HandleFunc("/api/compute/profiles", server.handleComputeProfiles)
	mux.HandleFunc("/api/clusters/", server.handleClusterStatus)
	// Phase 5 – Budget Alerts
	mux.HandleFunc("/api/billing/alerts", server.handleBudgetAlerts)
	// Phase 5 – Automated SDLC / Pipelines
	mux.HandleFunc("/api/pipelines", server.handlePipelines)
	mux.HandleFunc("/api/pipelines/promote", server.handlePipelinePromote)
	mux.HandleFunc("/api/pipelines/status", server.handlePipelineStatus)
	// Auth – login / logout / current user
	mux.HandleFunc("/api/auth/login", server.authHandlers.HandleLogin)
	mux.HandleFunc("/api/auth/logout", server.authHandlers.HandleLogout)
	mux.HandleFunc("/api/auth/me", server.authHandlers.HandleMe)
	// User management (admin only)
	mux.HandleFunc("/api/users", server.authHandlers.HandleUsers)
	mux.HandleFunc("/api/users/", server.authHandlers.HandleUser)
	// Role management
	mux.HandleFunc("/api/roles", server.authHandlers.HandleRoles)
	// Health / readiness probes
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})
	mux.HandleFunc("/readyz", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})
	mux.Handle("/metrics", telemetry.MetricsHandler())
	return telemetry.Middleware(auth.Middleware(store)(mux))
}

const indexHTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>One Human Corp Dashboard</title>
</head>
<body>
  <h1>One Human Corp Dashboard</h1>
  <p>Send Message to an agent or meeting room using the API.</p>
  <p>View Role Playbooks and agent skill sets in the Settings panel.</p>
  <div id="root"></div>
</body>
</html>`

func (s *Server) handleIndex(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(indexHTML))
}

func (s *Server) handleCosts(w http.ResponseWriter, _ *http.Request) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	writeJSON(w, s.tracker.Summary(s.org.ID))
}

func (s *Server) handleDashboard(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, s.snapshot())
}

func (s *Server) handleDevSeed(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)

	var payload seedRequest
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&payload); err != nil {
		http.Error(w, "invalid JSON payload", http.StatusBadRequest)
		return
	}

	org, hub, tracker, err := seededScenario(payload.Scenario, time.Now().UTC())
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	s.mu.Lock()
	s.org = org
	s.hub = hub
	s.tracker = tracker

	mockHandoff := HandoffPackage{
		ID:             "handoff-" + time.Now().UTC().Format("20060102150405"),
		FromAgentID:    "swe-1",
		ToHumanRole:    "CEO",
		Intent:         "Merge conflict resolution required for legacy billing module.",
		FailedAttempts: 3,
		CurrentState:   `{"Step_1_Code_Checkout": "SUCCESS", "Step_2_Dependency_Install": "SUCCESS", "Step_3_Test_Suite": "FAIL: TypeError in billing_test.go", "Step_4_Auto_Remediation": "SIGKILL: Timeout after 30s"}`,
		Status:         "pending",
		CreatedAt:      time.Now().UTC(),
	}
	s.handoffs = append(s.handoffs, mockHandoff)
	s.hub.LogEvent(mockHandoff)

	mockPipeline := Pipeline{
		ID:          "pipe-seed-" + time.Now().UTC().Format("20060102150405"),
		Name:        "feat-billing-seed",
		Status:      PipelineStatusStaging,
		Branch:      "feature/billing",
		StagingURL:  "https://staging.acme.com",
		InitiatedBy: "admin",
		CreatedAt:   time.Now().UTC(),
		UpdatedAt:   time.Now().UTC(),
	}
	s.pipelines = append(s.pipelines, mockPipeline)

	snapshot := s.snapshotLocked()
	s.mu.Unlock()

	writeJSON(w, snapshot)
}

// handleAgentProviders lists all registered external agent providers and their
// authentication status.  Responds to GET only.

// providerAuthRequest carries credentials for authenticating with an agent provider.
type providerAuthRequest struct {
	ProviderType string            `json:"providerType"`
	APIKey       string            `json:"apiKey,omitempty"`
	OAuthToken   string            `json:"oauthToken,omitempty"`
	Extra        map[string]string `json:"extra,omitempty"`
}

// handleAgentProviderAuth accepts POST requests to authenticate with an external
// agent provider.  Credentials are stored in memory and forwarded to any
// subsequently hired agent of that provider type.

type mcpRegisterRequest struct {
	Tool     MCPTool `json:"tool"`
	SPIFFEID string  `json:"spiffeId"`
}

func (s *Server) handleMCPRegister(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)

	var req mcpRegisterRequest
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		http.Error(w, "invalid JSON payload", http.StatusBadRequest)
		return
	}

	if req.Tool.ID == "" || req.Tool.Name == "" {
		http.Error(w, "tool ID and name are required", http.StatusBadRequest)
		return
	}

	if err := interop.ValidateSPIFFEID(req.SPIFFEID); err != nil {
		http.Error(w, "invalid SPIFFE ID: "+err.Error(), http.StatusForbidden)
		return
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	// Check if tool already exists
	for i, t := range s.dynamicMCPTools {
		if t.ID == req.Tool.ID {
			s.dynamicMCPTools[i] = req.Tool
			writeJSON(w, map[string]interface{}{"status": "updated", "tool": req.Tool})
			return
		}
	}

	s.dynamicMCPTools = append(s.dynamicMCPTools, req.Tool)
	writeJSON(w, map[string]interface{}{"status": "registered", "tool": req.Tool})
}

func (s *Server) handleMCPTools(w http.ResponseWriter, _ *http.Request) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	writeJSON(w, s.dynamicMCPTools)
}

func (s *Server) snapshot() dashboardSnapshot {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.snapshotLocked()
}

func (s *Server) snapshotLocked() dashboardSnapshot {
	agents := s.hub.Agents()
	return dashboardSnapshot{
		Organization: s.org,
		Meetings:     s.hub.Meetings(),
		Costs:        s.tracker.Summary(s.org.ID),
		Agents:       agents,
		Statuses:     summarizeStatuses(agents),
		UpdatedAt:    time.Now().UTC(),
	}
}

func seededScenario(name string, now time.Time) (domain.Organization, *orchestration.Hub, *billing.Tracker, error) {
	scenario := name
	if scenario == "" {
		scenario = "launch-readiness"
	}

	switch scenario {
	case "launch-readiness":
		return seededLaunchReadiness(now)
	case "digital-marketing":
		return seededDigitalMarketing(now)
	case "accounting":
		return seededAccounting(now)
	default:
		return domain.Organization{}, nil, nil, errors.New("unsupported seed scenario")
	}
}

func seededLaunchReadiness(now time.Time) (domain.Organization, *orchestration.Hub, *billing.Tracker, error) {
	org := domain.NewSoftwareCompany("demo", "Demo Software Company", "Human CEO", now.UTC())
	hub := orchestration.NewHub()
	hub.RegisterAgent(orchestration.Agent{ID: "pm-1", Name: "Product Manager", Role: "PRODUCT_MANAGER", OrganizationID: org.ID})
	hub.RegisterAgent(orchestration.Agent{ID: "swe-1", Name: "Software Engineer", Role: "SOFTWARE_ENGINEER", OrganizationID: org.ID})
	hub.RegisterAgent(orchestration.Agent{ID: "ux-1", Name: "Design Lead", Role: "DESIGNER", OrganizationID: org.ID})
	hub.RegisterAgent(orchestration.Agent{ID: "qa-1", Name: "QA Lead", Role: "QA_TESTER", OrganizationID: org.ID})
	hub.RegisterAgent(orchestration.Agent{ID: "sec-1", Name: "Security Auditor", Role: "SECURITY_ENGINEER", OrganizationID: org.ID})
	hub.RegisterAgent(orchestration.Agent{ID: "CEO", Name: "Human CEO", Role: "CEO", OrganizationID: org.ID})
	hub.OpenMeetingWithAgenda("launch-readiness", "Review launch blockers, sign-off on reliability checklist, assign post-launch owners.", []string{"pm-1", "swe-1", "ux-1", "qa-1", "sec-1", "CEO"})

	_ = hub.Publish(orchestration.Message{
		ID:         "seed-1",
		FromAgent:  "pm-1",
		ToAgent:    "swe-1",
		Type:       orchestration.EventTask,
		Content:    "Ship the reliability checklist before launch.",
		MeetingID:  "launch-readiness",
		OccurredAt: now.Add(-6 * time.Minute),
	})
	_ = hub.Publish(orchestration.Message{
		ID:         "seed-2",
		FromAgent:  "swe-1",
		ToAgent:    "pm-1",
		Type:       orchestration.EventStatus,
		Content:    "Checklist is 90% complete. Waiting on design assets for the final error states.",
		MeetingID:  "launch-readiness",
		OccurredAt: now.Add(-4 * time.Minute),
	})
	_ = hub.Publish(orchestration.Message{
		ID:         "seed-3",
		FromAgent:  "ux-1",
		ToAgent:    "pm-1",
		Type:       orchestration.EventStatus,
		Content:    "Design QA pass completed with no blockers. Assets pushed to main.",
		MeetingID:  "launch-readiness",
		OccurredAt: now.Add(-2 * time.Minute),
	})

	msgID := "seed-4"
	_ = hub.Publish(orchestration.Message{
		ID:         msgID,
		FromAgent:  "pm-1",
		ToAgent:    "CEO",
		Type:       orchestration.EventApprovalNeeded,
		Content:    "All pre-launch checks passed. Requesting final CEO approval to deploy to production.",
		MeetingID:  "launch-readiness",
		OccurredAt: now.Add(-1 * time.Minute),
	})

	tracker := billing.NewTracker(billing.DefaultCatalog)
	_, _ = tracker.Track(billing.Usage{
		AgentID:          "pm-1",
		AgentRole:        "PRODUCT_MANAGER",
		OrganizationID:   org.ID,
		Model:            "gpt-4o-mini",
		PromptTokens:     1200,
		CompletionTokens: 400,
		OccurredAt:       now.Add(-10 * time.Minute),
	})
	_, _ = tracker.Track(billing.Usage{
		AgentID:          "swe-1",
		AgentRole:        "SOFTWARE_ENGINEER",
		OrganizationID:   org.ID,
		Model:            "gpt-4o",
		PromptTokens:     2600,
		CompletionTokens: 900,
		OccurredAt:       now.Add(-8 * time.Minute),
	})
	_, _ = tracker.Track(billing.Usage{
		AgentID:          "ux-1",
		AgentRole:        "DESIGNER",
		OrganizationID:   org.ID,
		Model:            "gpt-4o-mini",
		PromptTokens:     900,
		CompletionTokens: 300,
		OccurredAt:       now.Add(-6 * time.Minute),
	})

	return org, hub, tracker, nil
}

func seededDigitalMarketing(now time.Time) (domain.Organization, *orchestration.Hub, *billing.Tracker, error) {
	org := domain.NewDigitalMarketingAgency("dma-demo", "Demo Digital Agency", "Human CEO", now.UTC())
	hub := orchestration.NewHub()
	hub.RegisterAgent(orchestration.Agent{ID: "growth-1", Name: "Growth Agent", Role: "GROWTH_AGENT", OrganizationID: org.ID})
	hub.RegisterAgent(orchestration.Agent{ID: "content-1", Name: "Content Strategist", Role: "CONTENT_STRATEGIST", OrganizationID: org.ID})
	hub.RegisterAgent(orchestration.Agent{ID: "seo-1", Name: "SEO Specialist", Role: "SEO_SPECIALIST", OrganizationID: org.ID})
	hub.OpenMeetingWithAgenda("campaign-kickoff", "Plan Q2 acquisition campaigns and assign channel ownership.", []string{"growth-1", "content-1", "seo-1"})

	_ = hub.Publish(orchestration.Message{
		ID:         "seed-dma-1",
		FromAgent:  "growth-1",
		ToAgent:    "content-1",
		Type:       orchestration.EventTask,
		Content:    "Draft top-of-funnel blog series targeting enterprise SaaS buyers.",
		MeetingID:  "campaign-kickoff",
		OccurredAt: now.Add(-5 * time.Minute),
	})

	tracker := billing.NewTracker(billing.DefaultCatalog)
	_, _ = tracker.Track(billing.Usage{
		AgentID:          "growth-1",
		AgentRole:        "GROWTH_AGENT",
		OrganizationID:   org.ID,
		Model:            "gpt-4o",
		PromptTokens:     1800,
		CompletionTokens: 600,
		OccurredAt:       now.Add(-5 * time.Minute),
	})

	return org, hub, tracker, nil
}

func seededAccounting(now time.Time) (domain.Organization, *orchestration.Hub, *billing.Tracker, error) {
	org := domain.NewAccountingFirm("acc-demo", "Demo Accounting Firm", "Human CEO", now.UTC())
	hub := orchestration.NewHub()
	hub.RegisterAgent(orchestration.Agent{ID: "bookkeeper-1", Name: "Bookkeeper", Role: "BOOKKEEPER", OrganizationID: org.ID})
	hub.RegisterAgent(orchestration.Agent{ID: "tax-1", Name: "Tax Specialist", Role: "TAX_SPECIALIST", OrganizationID: org.ID})
	hub.RegisterAgent(orchestration.Agent{ID: "cfo-1", Name: "CFO", Role: "CFO", OrganizationID: org.ID})
	hub.OpenMeetingWithAgenda("month-close", "Reconcile April ledger, prepare estimated tax liability, and review payroll entries.", []string{"bookkeeper-1", "tax-1", "cfo-1"})

	_ = hub.Publish(orchestration.Message{
		ID:         "seed-acc-1",
		FromAgent:  "cfo-1",
		ToAgent:    "bookkeeper-1",
		Type:       orchestration.EventTask,
		Content:    "Reconcile bank feeds and categorize uncategorized transactions before EOD.",
		MeetingID:  "month-close",
		OccurredAt: now.Add(-3 * time.Minute),
	})

	tracker := billing.NewTracker(billing.DefaultCatalog)
	_, _ = tracker.Track(billing.Usage{
		AgentID:          "cfo-1",
		AgentRole:        "CFO",
		OrganizationID:   org.ID,
		Model:            "claude-3.5-sonnet",
		PromptTokens:     1500,
		CompletionTokens: 500,
		OccurredAt:       now.Add(-3 * time.Minute),
	})

	return org, hub, tracker, nil
}

func writeJSON(w http.ResponseWriter, value any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(value)
}

// ── Chat test handler ─────────────────────────────────────────────────────────

type chatTestRequest struct {
	IntegrationID string `json:"integrationId"`
	BotToken      string `json:"botToken,omitempty"`
	ChatID        string `json:"chatId,omitempty"`
	WebhookURL    string `json:"webhookUrl,omitempty"`
	APIToken      string `json:"apiToken,omitempty"`
}

// ── MCP tool invocation ───────────────────────────────────────────────────────

type mcpInvokeRequest struct {
	ToolID   string          `json:"toolId"`
	Action   string          `json:"action"`
	Params   json.RawMessage `json:"params"`
	AgentID  string          `json:"agentId,omitempty"`
	SPIFFEID string          `json:"spiffeId,omitempty"`
}

type chatToolParams struct {
	IntegrationID string `json:"integrationId,omitempty"`
	Channel       string `json:"channel,omitempty"`
	FromAgent     string `json:"fromAgent,omitempty"`
	Content       string `json:"content"`
	ThreadID      string `json:"threadId,omitempty"`
}

type gitToolParams struct {
	IntegrationID string `json:"integrationId,omitempty"`
	Repository    string `json:"repository"`
	Title         string `json:"title"`
	Body          string `json:"body"`
	SourceBranch  string `json:"sourceBranch"`
	TargetBranch  string `json:"targetBranch,omitempty"`
	CreatedBy     string `json:"createdBy"`
}

type issueToolParams struct {
	IntegrationID string `json:"integrationId,omitempty"`
	Project       string `json:"project"`
	Title         string `json:"title"`
	Description   string `json:"description"`
	CreatedBy     string `json:"createdBy"`
	Priority      string `json:"priority"`
}

func (s *Server) handleMCPInvoke(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Enforce a strict 1MB limit on tool payloads to prevent DOS via massive JSON strings.
	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)

	var req mcpInvokeRequest
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		http.Error(w, "invalid JSON payload", http.StatusBadRequest)
		return
	}
	if req.ToolID == "" {
		http.Error(w, "toolId is required", http.StatusBadRequest)
		return
	}
	if len(req.Params) == 0 {
		req.Params = []byte("{}")
	}

	if req.SPIFFEID != "" {
		if err := interop.ValidateSPIFFEID(req.SPIFFEID); err != nil {
			http.Error(w, "invalid SPIFFE ID: "+err.Error(), http.StatusForbidden)
			return
		}
	}

	// Check if the agent is rate-limited for this tool
	rateLimitKey := req.AgentID + ":" + req.ToolID
	s.mu.Lock()
	if s.rateLimitStates == nil {
		s.rateLimitStates = make(map[string]*RateLimitState)
	}
	state, exists := s.rateLimitStates[rateLimitKey]
	if !exists {
		state = &RateLimitState{Backoff: 1 * time.Second}
		s.rateLimitStates[rateLimitKey] = state
	}
	s.mu.Unlock()

	s.mu.RLock()
	if state.Failures >= 3 {
		s.mu.RUnlock()
		http.Error(w, "Max retries exceeded. Hard failure.", http.StatusTooManyRequests)
		return
	}
	if time.Since(state.LastFailure) < state.Backoff && state.Failures > 0 {
		s.mu.RUnlock()
		http.Error(w, "Rate limited. Please backoff.", http.StatusTooManyRequests)
		return
	}
	s.mu.RUnlock()

	result, err := s.invokeMCPTool(req)

	s.mu.Lock()
	if err != nil {
		// e.g. "Rate limited" or "429" or missing tool handling
		if strings.Contains(err.Error(), "429") || strings.Contains(err.Error(), "rate limited") {
			state.Failures++
			state.LastFailure = time.Now()
			state.Backoff = time.Duration(1<<state.Failures) * time.Second // Exponential backoff

			// Record failure event
			if req.AgentID != "" {
				msg := orchestration.Message{
					ID:         "rl-" + time.Now().UTC().Format("20060102150405.999999999"),
					FromAgent:  "SYSTEM",
					ToAgent:    req.AgentID,
					Type:       "ToolExecutionRateLimiting",
					Content:    fmt.Sprintf(`{"toolId": "%s", "status": "failed", "reason": "rate_limited", "backoff": "%s", "failures": %d}`, req.ToolID, state.Backoff.String(), state.Failures),
					OccurredAt: time.Now().UTC(),
				}
				_ = s.hub.Publish(msg)

				s.hub.LogEvent(msg)
			}

			s.mu.Unlock()
			if state.Failures >= 3 {
				http.Error(w, "Max retries exceeded. Hard failure.", http.StatusTooManyRequests)
			} else {
				http.Error(w, "Rate limited. Please backoff.", http.StatusTooManyRequests)
			}
			return
		} else if strings.Contains(err.Error(), "not found") || strings.Contains(err.Error(), "unknown tool") || strings.Contains(err.Error(), "invalid JSON-RPC") {
			if req.AgentID != "" {
				if agent, ok := s.hub.Agent(req.AgentID); ok {
					agent.Status = orchestration.StatusWaitingForTools
					s.hub.RegisterAgent(agent)
				}
			}
			s.mu.Unlock()
			http.Error(w, err.Error(), http.StatusNotFound)
			return
		}
	} else {
		// Reset on success
		delete(s.rateLimitStates, rateLimitKey) // Prevent unbounded memory leak

		if req.AgentID != "" {
			msg := orchestration.Message{
				ID:         "rl-succ-" + time.Now().UTC().Format("20060102150405.999999999"),
				FromAgent:  "SYSTEM",
				ToAgent:    req.AgentID,
				Type:       "ToolExecutionRateLimiting",
				Content:    fmt.Sprintf(`{"toolId": "%s", "status": "success"}`, req.ToolID),
				OccurredAt: time.Now().UTC(),
			}
			_ = s.hub.Publish(msg)

			s.hub.LogEvent(msg)
		}
	}
	s.mu.Unlock()

	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	writeJSON(w, result)
}

func (s *Server) invokeMCPTool(req mcpInvokeRequest) (map[string]any, error) {
	// Emit structured trace for MCP tool invocation
	slog.Info("agent execution trace",
		"component", "telemetry",
		"api", "invokeMCPTool",
		"tool_id", req.ToolID,
		"action", req.Action,
	)

	switch req.ToolID {
	// ── Communication tools ───────────────────────────────────────────────────
	case "telegram-mcp", "slack-mcp", "teams-mcp":
		var p chatToolParams
		// ⚡ BOLT: [JSON serialization thrashing on tool payloads] - Randomized Selection from Top 5
		// Eliminated json.NewDecoder allocations on hot native paths using json.Unmarshal.
		if err := json.Unmarshal(req.Params, &p); err != nil {
			return nil, errors.New("invalid chat tool parameters")
		}

		integrationID := p.IntegrationID
		if integrationID == "" {
			switch req.ToolID {
			case "telegram-mcp":
				integrationID = "telegram"
			case "slack-mcp":
				integrationID = "slack"
			case "teams-mcp":
				integrationID = "teams"
			}
		}

		channel := p.Channel
		fromAgent := p.FromAgent
		content := p.Content
		threadID := p.ThreadID

		if content == "" {
			return nil, errors.New("content is required")
		}
		if fromAgent == "" {
			fromAgent = "system"
		}
		// Fall back to the configured chatspace if no channel given.
		if channel == "" {
			if integ, ok := s.integReg.Integration(integrationID); ok {
				channel = integ.Chatspace
			}
		}
		if channel == "" {
			return nil, errors.New("channel is required — configure the integration's chatspace first")
		}
		msg, err := s.integReg.SendChatMessage(integrationID, channel, fromAgent, content, threadID, time.Now().UTC())
		if err != nil {
			return nil, err
		}
		return map[string]any{"message": msg, "delivered": true}, nil

	// ── Git tools ─────────────────────────────────────────────────────────────
	case "git-mcp":
		var p gitToolParams
		// ⚡ BOLT: [JSON serialization thrashing on tool payloads] - Randomized Selection from Top 5
		// Eliminated json.NewDecoder allocations on hot native paths using json.Unmarshal.
		if err := json.Unmarshal(req.Params, &p); err != nil {
			return nil, errors.New("invalid git tool parameters")
		}

		integrationID := p.IntegrationID
		if integrationID == "" {
			integrationID = "github"
		}

		repo := p.Repository
		title := p.Title
		body := p.Body
		source := p.SourceBranch
		target := p.TargetBranch
		createdBy := p.CreatedBy

		if target == "" {
			target = "main"
		}
		pr, err := s.integReg.CreatePullRequest(integrationID, repo, title, body, source, target, createdBy, time.Now().UTC())
		if err != nil {
			return nil, err
		}
		return map[string]any{"pullRequest": pr}, nil

	// ── Issue tracker tools ───────────────────────────────────────────────────
	case "jira-mcp", "linear-mcp":
		var p issueToolParams
		// ⚡ BOLT: [JSON serialization thrashing on tool payloads] - Randomized Selection from Top 5
		// Eliminated json.NewDecoder allocations on hot native paths using json.Unmarshal.
		if err := json.Unmarshal(req.Params, &p); err != nil {
			return nil, errors.New("invalid issue tool parameters")
		}

		integrationID := p.IntegrationID
		if integrationID == "" {
			if req.ToolID == "jira-mcp" {
				integrationID = "jira"
			} else {
				integrationID = "linear"
			}
		}

		project := p.Project
		title := p.Title
		description := p.Description
		createdBy := p.CreatedBy
		priority := p.Priority

		issue, err := s.integReg.CreateIssue(integrationID, project, title, description, createdBy,
			integrations.IssuePriority(priority), nil, time.Now().UTC())
		if err != nil {
			return nil, err
		}
		return map[string]any{"issue": issue}, nil

	// ── Unimplemented tools — return a structured acknowledgement ─────────────
	default:
		s.mu.RLock()
		found := false
		for _, t := range s.dynamicMCPTools {
			if t.ID == req.ToolID {
				found = true
				break
			}
		}
		s.mu.RUnlock()

		if !found {
			return nil, fmt.Errorf("unknown tool: %s", req.ToolID)
		}

		return map[string]any{
			"toolId":  req.ToolID,
			"status":  "invoked",
			"message": "Tool invocation recorded. Connect the corresponding service integration to enable live execution.",
		}, nil
	}
}

func summarizeStatuses(agents []orchestration.Agent) []statusCount {
	counts := map[orchestration.Status]int{
		orchestration.StatusIdle:      0,
		orchestration.StatusActive:    0,
		orchestration.StatusInMeeting: 0,
		orchestration.StatusBlocked:   0,
	}
	for _, agent := range agents {
		counts[agent.Status]++
	}

	statuses := make([]statusCount, 0, len(counts))
	for _, status := range statusOrder {
		statuses = append(statuses, statusCount{
			Status: status,
			Count:  counts[status],
		})
	}

	return statuses
}

// ── Approval / Confidence Gating Handlers ─────────────────────────────────────

// ── Warm Handoff Handlers ─────────────────────────────────────────────────────

// ── Identity Management Handler ───────────────────────────────────────────────

// ── Skill Pack Handlers ───────────────────────────────────────────────────────

// ── Snapshot Handlers ─────────────────────────────────────────────────────────

// seededScenarioByDomain re-seeds an org from its domain identifier.
func seededScenarioByDomain(dom string, now time.Time) (domain.Organization, *orchestration.Hub, *billing.Tracker, error) {
	switch dom {
	case "software_company":
		return seededLaunchReadiness(now)
	case "digital_marketing_agency":
		return seededDigitalMarketing(now)
	case "accounting_firm":
		return seededAccounting(now)
	default:
		return domain.Organization{}, nil, nil, errors.New("unsupported domain for restore")
	}
}

// ── Marketplace Handler ───────────────────────────────────────────────────────

// ── Analytics Handler ─────────────────────────────────────────────────────────

// ── Default Data Factories ────────────────────────────────────────────────────

func defaultSkillPacks() []SkillPack {
	now := time.Now().UTC()
	return []SkillPack{
		{
			ID:          "builtin-core-ai",
			Name:        "Core AI Skills",
			Domain:      "all",
			Description: "Foundational reasoning, summarization, and context management capabilities shared by all agents.",
			Source:      "builtin",
			Roles: []SkillPackRole{
				{Role: "ALL", BasePrompt: "You are a highly capable AI agent. Summarize long discussions before passing context to the next agent."},
			},
			ImportedAt: now,
		},
		{
			ID:          "builtin-software-dev",
			Name:        "Software Development Mastery",
			Domain:      "software_company",
			Description: "Advanced engineering skills: clean code, TDD, security-first development, and CI/CD automation.",
			Source:      "builtin",
			Roles: []SkillPackRole{
				{Role: "SOFTWARE_ENGINEER", BasePrompt: "Write well-tested, secure, and maintainable code. Follow TDD practices."},
				{Role: "QA_TESTER", BasePrompt: "Design comprehensive test suites covering edge cases and regressions."},
			},
			ImportedAt: now,
		},
		{
			ID:          "builtin-marketing-automation",
			Name:        "Marketing Automation Suite",
			Domain:      "digital_marketing_agency",
			Description: "Data-driven growth hacking, SEO optimization, and paid media management at scale.",
			Source:      "builtin",
			Roles: []SkillPackRole{
				{Role: "GROWTH_AGENT", BasePrompt: "Identify high-value acquisition channels using data. Run A/B tests continuously."},
			},
			ImportedAt: now,
		},
		{
			ID:          "builtin-financial-ops",
			Name:        "Financial Operations Pack",
			Domain:      "accounting_firm",
			Description: "GAAP-compliant bookkeeping, tax optimization, and audit preparation.",
			Source:      "builtin",
			Roles: []SkillPackRole{
				{Role: "BOOKKEEPER", BasePrompt: "Maintain double-entry books with 100% accuracy. Reconcile all accounts daily."},
			},
			ImportedAt: now,
		},
	}
}

func defaultMarketplaceItems() []MarketplaceItem {
	return []MarketplaceItem{
		{
			ID:          "mkt-tiger-team",
			Name:        "Tiger Team Sprint Pack",
			Type:        "skill_pack",
			Author:      "OneHumanCorp",
			Description: "Spin up a temporary 5-agent strike force for a time-boxed launch sprint.",
			Downloads:   1420,
			Rating:      4.8,
			Tags:        []string{"sprint", "launch", "team"},
		},
		{
			ID:          "mkt-ecommerce-domain",
			Name:        "E-Commerce Operations Domain",
			Type:        "domain",
			Author:      "Community",
			Description: "Full e-commerce organization with catalog, inventory, customer support, and growth roles.",
			Downloads:   892,
			Rating:      4.6,
			Tags:        []string{"ecommerce", "retail", "domain"},
		},
		{
			ID:          "mkt-crm-integration",
			Name:        "CRM Intelligence Pack",
			Type:        "tool",
			Author:      "SalesStack",
			Description: "Bi-directional Salesforce / HubSpot sync for Sales and Growth agents.",
			Downloads:   2100,
			Rating:      4.9,
			Tags:        []string{"crm", "sales", "integration"},
		},
		{
			ID:          "mkt-code-review-agent",
			Name:        "Autonomous Code Review Agent",
			Type:        "agent",
			Author:      "DevBot Labs",
			Description: "Specialized SWE agent trained on your codebase conventions. Reviews PRs for style, correctness, and test coverage.",
			Downloads:   3750,
			Rating:      4.7,
			Tags:        []string{"code-review", "engineering", "agent"},
		},
		{
			ID:          "mkt-guardian-agent",
			Name:        "Guardian Agent Pro",
			Type:        "agent",
			Author:      "SafeOps",
			Description: "Advanced confidence-gating agent with configurable spend thresholds and Slack/email HITL notifications.",
			Downloads:   980,
			Rating:      4.8,
			Tags:        []string{"security", "approval", "hitl"},
		},
	}
}

// ── Integration request/response types ────────────────────────────────────────

type integrationConnectRequest struct {
	IntegrationID string `json:"integrationId"`
	BaseURL       string `json:"baseUrl,omitempty"`
	// Chat credentials — stored server-side, never returned to the client.
	BotToken   string `json:"botToken,omitempty"`
	ChatID     string `json:"chatId,omitempty"`
	WebhookURL string `json:"webhookUrl,omitempty"`
	APIToken   string `json:"apiToken,omitempty"`
}

type integrationDisconnectRequest struct {
	IntegrationID string `json:"integrationId"`
}

type chatSendRequest struct {
	IntegrationID string `json:"integrationId"`
	Channel       string `json:"channel"`
	FromAgent     string `json:"fromAgent"`
	Content       string `json:"content"`
	ThreadID      string `json:"threadId,omitempty"`
}

type prCreateRequest struct {
	IntegrationID string `json:"integrationId"`
	Repository    string `json:"repository"`
	Title         string `json:"title"`
	Body          string `json:"body,omitempty"`
	SourceBranch  string `json:"sourceBranch"`
	TargetBranch  string `json:"targetBranch"`
	CreatedBy     string `json:"createdBy,omitempty"`
}

type prActionRequest struct {
	PRID string `json:"prId"`
}

type issueCreateRequest struct {
	IntegrationID string   `json:"integrationId"`
	Project       string   `json:"project"`
	Title         string   `json:"title"`
	Description   string   `json:"description,omitempty"`
	CreatedBy     string   `json:"createdBy,omitempty"`
	Priority      string   `json:"priority,omitempty"`
	Labels        []string `json:"labels,omitempty"`
}

type issueStatusRequest struct {
	IssueID string `json:"issueId"`
	Status  string `json:"status"`
}

type issueAssignRequest struct {
	IssueID  string `json:"issueId"`
	Assignee string `json:"assignee"`
}

// ── Integration handlers ──────────────────────────────────────────────────────

// ── Chat handlers ─────────────────────────────────────────────────────────────

// ── Git handlers ──────────────────────────────────────────────────────────────

// ── Issue tracker handlers ────────────────────────────────────────────────────

// ── B2B Collaboration ─────────────────────────────────────────────────────────

// TrustAgreementStatus represents the lifecycle phase of a federated trust agreement, governing encrypted cross-cluster agent communication.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type TrustAgreementStatus string

const (
	// TrustStatusPending indicates a proposed B2B federation link currently awaiting cryptographic SPIFFE handshake verification.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	TrustStatusPending TrustAgreementStatus = "PENDING"
	// TrustStatusActive indicates a fully verified B2B federation link, permitting bidirectional cross-org agent collaboration.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	TrustStatusActive TrustAgreementStatus = "ACTIVE"
	// TrustStatusRevoked indicates a explicitly terminated B2B federation link, instantly nullifying all associated access tokens.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	TrustStatusRevoked TrustAgreementStatus = "REVOKED"
)

// TrustAgreement establishes a cryptographically verified, federated trust relationship between two distinct One Human Corp deployments using SPIFFE-federated JWTs.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type TrustAgreement struct {
	ID           string               `json:"id"`
	PartnerOrg   string               `json:"partnerOrg"`
	PartnerJWKS  string               `json:"partnerJwksUrl"`
	AllowedRoles []string             `json:"allowedRoles"`
	Status       TrustAgreementStatus `json:"status"`
	CreatedAt    time.Time            `json:"createdAt"`
}

type b2bHandshakeRequest struct {
	PartnerOrg   string   `json:"partnerOrg"`
	PartnerJWKS  string   `json:"partnerJwksUrl"`
	AllowedRoles []string `json:"allowedRoles"`
}

// ── Autonomous SRE / Incident Management ─────────────────────────────────────

// IncidentSeverity classifies the blast radius of an operational anomaly to determine the SRE agent's escalation path.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type IncidentSeverity string

const (
	// SeverityP0 represents a catastrophic platform failure requiring immediate, synchronous human and SRE agent intervention.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	SeverityP0 IncidentSeverity = "P0"
	// SeverityP1 represents a severe degradation of a critical business path, triggering immediate automated remediation attempts.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	SeverityP1 IncidentSeverity = "P1"
	// SeverityP2 represents a localized, non-critical issue that will be asynchronously triaged by SRE agents.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	SeverityP2 IncidentSeverity = "P2"
)

// IncidentStatus reflects the current automated investigation and remediation lifecycle state of an operational anomaly.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type IncidentStatus string

const (
	// IncidentStatusInvestigating indicates an SRE agent is actively analyzing logs, traces, and metrics to identify the root cause of an anomaly.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	IncidentStatusInvestigating IncidentStatus = "INVESTIGATING"
	// IncidentStatusProposed indicates an SRE agent has formulated a remediation plan and is awaiting human execution approval.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	IncidentStatusProposed IncidentStatus = "PROPOSED"
	// IncidentStatusResolved indicates the anomaly has been successfully mitigated and verified by automated checks.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	IncidentStatusResolved IncidentStatus = "RESOLVED"
)

// Incident represents a distinct operational event requiring SRE attention, encapsulating its timeline, severity context, and remediation history.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type Incident struct {
	ID               string           `json:"id"`
	Severity         IncidentSeverity `json:"severity"`
	Summary          string           `json:"summary"`
	RCA              string           `json:"rootCauseAnalysis"`
	ResolutionPlanID string           `json:"resolutionPlanId,omitempty"`
	Status           IncidentStatus   `json:"status"`
	CreatedAt        time.Time        `json:"createdAt"`
	UpdatedAt        time.Time        `json:"updatedAt"`
}

type incidentCreateRequest struct {
	Severity string `json:"severity"`
	Summary  string `json:"summary"`
	RCA      string `json:"rootCauseAnalysis,omitempty"`
}

type incidentStatusRequest struct {
	IncidentID       string `json:"incidentId"`
	Status           string `json:"status"`
	ResolutionPlanID string `json:"resolutionPlanId,omitempty"`
	RCA              string `json:"rootCauseAnalysis,omitempty"`
}

// ── Compute Optimization / Hardware-Aware Scheduling ─────────────────────────

// ComputeProfile defines the strict hardware constraints (CPU, Memory) and affinity rules for a specific agent role, ensuring optimal Kubernetes pod scheduling.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type ComputeProfile struct {
	RoleID             string    `json:"roleId"`
	MinVRAMGB          int       `json:"minVramGb"`
	PreferredGPUType   string    `json:"preferredGpuType"` // "h100", "a10g", "cpu"
	SchedulingPriority int       `json:"schedulingPriority"`
	CreatedAt          time.Time `json:"createdAt"`
}

type computeProfileRequest struct {
	RoleID             string `json:"roleId"`
	MinVRAMGB          int    `json:"minVramGb"`
	PreferredGPUType   string `json:"preferredGpuType"`
	SchedulingPriority int    `json:"schedulingPriority"`
}

// ClusterStatus reflects the real-time node health, resource capacity, and latency metrics of a remote Kubernetes region for workload placement.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type ClusterStatus struct {
	Region         string    `json:"region"`
	Status         string    `json:"status"` // healthy, degraded, offline
	LatencyMS      int       `json:"latencyMs"`
	AvailableNodes int       `json:"availableNodes"`
	CheckedAt      time.Time `json:"checkedAt"`
}

// ── Budget Alerts ─────────────────────────────────────────────────────────────

// defaultBudgetAlertNotifyPct is the default notification threshold (80 %).
const defaultBudgetAlertNotifyPct = 0.8

// BudgetAlert defines a proactive spending threshold with associated notification circuit-breaker behaviors to prevent runaway token costs.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type BudgetAlert struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organizationId"`
	ThresholdUSD   float64   `json:"thresholdUsd"`
	NotifyAtPct    float64   `json:"notifyAtPct"` // e.g. 0.8 → notify at 80 %
	Triggered      bool      `json:"triggered"`
	CreatedAt      time.Time `json:"createdAt"`
}

type budgetAlertRequest struct {
	OrganizationID string  `json:"organizationId"`
	ThresholdUSD   float64 `json:"thresholdUsd"`
	NotifyAtPct    float64 `json:"notifyAtPct"`
}

// ── Automated SDLC / Pipelines ────────────────────────────────────────────────

// PipelineStatus reflects the current lifecycle phase of an autonomous CI/CD implementation pipeline driven by agent collaboration.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type PipelineStatus string

const (
	// PipelineStatusPending indicates an autonomous pipeline has been created but has not yet commenced code generation.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	PipelineStatusPending PipelineStatus = "PENDING"
	// PipelineStatusImplementing indicates Software Engineer agents are actively iterating on code to satisfy the generated feature specification.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	PipelineStatusImplementing PipelineStatus = "IMPLEMENTING"
	// PipelineStatusTesting indicates QA agents are actively executing and verifying the implementation against the automated test suites.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	PipelineStatusTesting PipelineStatus = "TESTING"
	// PipelineStatusStaging indicates the feature has passed automated checks and is deployed to an ephemeral environment for final human review.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	PipelineStatusStaging PipelineStatus = "STAGING"
	// PipelineStatusPromoted indicates the feature has been successfully merged and deployed to the production environment.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	PipelineStatusPromoted PipelineStatus = "PROMOTED"
	// PipelineStatusFailed indicates the pipeline encountered an unrecoverable compilation error or test failure requiring manual intervention.
	// Accepts no parameters.
	// Returns nothing.
	// Produces no errors.
	// Has no side effects.
	PipelineStatusFailed PipelineStatus = "FAILED"
)

// Pipeline represents an autonomous, end-to-end implementation workflow, tracking a feature's progression from approved spec to a deployed artifact.
// Accepts no parameters.
// Returns nothing.
// Produces no errors.
// Has no side effects.
type Pipeline struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Status      PipelineStatus `json:"status"`
	Branch      string         `json:"branch"`
	StagingURL  string         `json:"stagingUrl,omitempty"`
	InitiatedBy string         `json:"initiatedBy"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type pipelineCreateRequest struct {
	Name        string `json:"name"`
	Branch      string `json:"branch"`
	InitiatedBy string `json:"initiatedBy"`
}

type pipelinePromoteRequest struct {
	PipelineID string `json:"pipelineId"`
	ApprovedBy string `json:"approvedBy"`
}
