apiVersion: v2
name: ohc
description: One Human Corp backend/frontend chart
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: redis
    version: 20.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 16.4.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled